///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntryTranslationMemory recording.
    /// </summary>
    [TestModule("34a97516-17ee-49aa-813d-492d99bc91d9", ModuleType.Recording, 1)]
    public partial class AddEntryTranslationMemory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static AddEntryTranslationMemory instance = new AddEntryTranslationMemory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntryTranslationMemory()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntryTranslationMemory Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage' at 49;16.", repo.SYSTRANDictionaryManager.EnglishSourceLanguageInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage.Click("49;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'I missed you.' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(1));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("I missed you.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage' at 26;11.", repo.SYSTRANDictionaryManager.FrenchTargetLanguageInfo, new RecordItemIndex(2));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage.Click("26;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'J'ai manqué' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(3));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("J'ai manqué");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.Save' at 10;16.", repo.SYSTRANDictionaryManager.SaveInfo, new RecordItemIndex(4));
            repo.SYSTRANDictionaryManager.Save.Click("10;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
