///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CodingConfidenceIndicator recording.
    /// </summary>
    [TestModule("d2fddaaa-6feb-4d96-b826-e55b0ef5b52b", ModuleType.Recording, 1)]
    public partial class CodingConfidenceIndicator : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testtooltipRepository repository.
        /// </summary>
        public static testtooltipRepository repo = testtooltipRepository.Instance;

        static CodingConfidenceIndicator instance = new CodingConfidenceIndicator();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CodingConfidenceIndicator()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CodingConfidenceIndicator Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.File' at 14;11.", repo.SYSTRANDictionaryManager.FileInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.File.Click("14;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.MenuPopup' at 27;9.", repo.SystranDictionaryManager1.MenuPopupInfo, new RecordItemIndex(1));
            repo.SystranDictionaryManager1.MenuPopup.Click("27;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea21' at 37;10.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea21Info, new RecordItemIndex(2));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea21.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem2' at 38;3.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem2Info, new RecordItemIndex(3));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem2.Click("38;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea11' at 35;9.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea11Info, new RecordItemIndex(4));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea11.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'DictionaryPropertiesBaseForm.TxtDictName'.", repo.DictionaryPropertiesBaseForm.TxtDictNameInfo, new RecordItemIndex(5));
            repo.DictionaryPropertiesBaseForm.TxtDictName.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea211' at 36;15.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea211Info, new RecordItemIndex(6));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea211.Click("36;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'DictionaryPropertiesBaseForm.TxtAuthor'.", repo.DictionaryPropertiesBaseForm.TxtAuthorInfo, new RecordItemIndex(7));
            repo.DictionaryPropertiesBaseForm.TxtAuthor.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3' at 10;8.", repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3Info, new RecordItemIndex(8));
            repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem0' at 116;6.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem0Info, new RecordItemIndex(9));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem0.Click("116;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonOK' at 13;10.", repo.DictionaryPropertiesBaseForm.ButtonOKInfo, new RecordItemIndex(10));
            repo.DictionaryPropertiesBaseForm.ButtonOK.Click("13;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage' at 64;11.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguageInfo, new RecordItemIndex(11));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage.Click("64;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(12));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage' at 38;11.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguageInfo, new RecordItemIndex(13));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage.Click("38;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hi' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(14));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("hi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.CellID' at 19;15.", repo.SYSTRANDictionaryManager.MEntriesView.CellIDInfo, new RecordItemIndex(15));
            repo.SYSTRANDictionaryManager.MEntriesView.CellID.Click("19;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage1' at 44;12.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage1Info, new RecordItemIndex(16));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage1.Click("44;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row1'.", repo.SYSTRANDictionaryManager.MEntriesView.Row1Info, new RecordItemIndex(17));
            repo.SYSTRANDictionaryManager.MEntriesView.Row1.PressKeys("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage1' at 45;7.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage1Info, new RecordItemIndex(18));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage1.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bonjour' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row1'.", repo.SYSTRANDictionaryManager.MEntriesView.Row1Info, new RecordItemIndex(19));
            repo.SYSTRANDictionaryManager.MEntriesView.Row1.PressKeys("bonjour");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.CellID' at 8;6.", repo.SYSTRANDictionaryManager.MEntriesView.CellIDInfo, new RecordItemIndex(20));
            repo.SYSTRANDictionaryManager.MEntriesView.CellID.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage2' at 29;9.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage2Info, new RecordItemIndex(21));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage2.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'him' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row2'.", repo.SYSTRANDictionaryManager.MEntriesView.Row2Info, new RecordItemIndex(22));
            repo.SYSTRANDictionaryManager.MEntriesView.Row2.PressKeys("him");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage2' at 33;15.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage2Info, new RecordItemIndex(23));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage2.Click("33;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lui' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row2'.", repo.SYSTRANDictionaryManager.MEntriesView.Row2Info, new RecordItemIndex(24));
            repo.SYSTRANDictionaryManager.MEntriesView.Row2.PressKeys("lui");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.CellID' at 13;8.", repo.SYSTRANDictionaryManager.MEntriesView.CellIDInfo, new RecordItemIndex(25));
            repo.SYSTRANDictionaryManager.MEntriesView.CellID.Click("13;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage3' at 32;10.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage3Info, new RecordItemIndex(26));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage3.Click("32;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'him' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row3'.", repo.SYSTRANDictionaryManager.MEntriesView.Row3Info, new RecordItemIndex(27));
            repo.SYSTRANDictionaryManager.MEntriesView.Row3.PressKeys("him");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage3' at 32;13.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage3Info, new RecordItemIndex(28));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage3.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lui' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row3'.", repo.SYSTRANDictionaryManager.MEntriesView.Row3Info, new RecordItemIndex(29));
            repo.SYSTRANDictionaryManager.MEntriesView.Row3.PressKeys("lui");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.CellID' at 9;5.", repo.SYSTRANDictionaryManager.MEntriesView.CellIDInfo, new RecordItemIndex(30));
            repo.SYSTRANDictionaryManager.MEntriesView.CellID.Click("9;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage4' at 34;10.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage4Info, new RecordItemIndex(31));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage4.Click("34;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'I' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row4'.", repo.SYSTRANDictionaryManager.MEntriesView.Row4Info, new RecordItemIndex(32));
            repo.SYSTRANDictionaryManager.MEntriesView.Row4.PressKeys("I");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage4' at 48;13.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage4Info, new RecordItemIndex(33));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage4.Click("48;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Je' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row4'.", repo.SYSTRANDictionaryManager.MEntriesView.Row4Info, new RecordItemIndex(34));
            repo.SYSTRANDictionaryManager.MEntriesView.Row4.PressKeys("Je");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.CellID' at 18;4.", repo.SYSTRANDictionaryManager.MEntriesView.CellIDInfo, new RecordItemIndex(35));
            repo.SYSTRANDictionaryManager.MEntriesView.CellID.Click("18;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage5' at 40;11.", repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage5Info, new RecordItemIndex(36));
            repo.SYSTRANDictionaryManager.MEntriesView.EnglishSourceLanguage5.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'me' with focus on 'SYSTRANDictionaryManager.MEntriesView.Text'.", repo.SYSTRANDictionaryManager.MEntriesView.TextInfo, new RecordItemIndex(37));
            repo.SYSTRANDictionaryManager.MEntriesView.Text.PressKeys("me");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage5' at 40;11.", repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage5Info, new RecordItemIndex(38));
            repo.SYSTRANDictionaryManager.MEntriesView.FrenchTargetLanguage5.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Je' with focus on 'SYSTRANDictionaryManager.MEntriesView.Row5'.", repo.SYSTRANDictionaryManager.MEntriesView.Row5Info, new RecordItemIndex(39));
            repo.SYSTRANDictionaryManager.MEntriesView.Row5.PressKeys("Je");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.Save' at 10;8.", repo.SYSTRANDictionaryManager.SaveInfo, new RecordItemIndex(40));
            repo.SYSTRANDictionaryManager.Save.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='60') on item 'SYSTRANDictionaryManager.MEntriesView.Confidence'.", repo.SYSTRANDictionaryManager.MEntriesView.ConfidenceInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.SYSTRANDictionaryManager.MEntriesView.ConfidenceInfo, "Text", "60");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.UserDictionaries1' at 11;6.", repo.SYSTRANDictionaryManager.UserDictionaries1Info, new RecordItemIndex(42));
            repo.SYSTRANDictionaryManager.UserDictionaries1.Click("11;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.TreeItemENFRTest' at 69;8.", repo.SYSTRANDictionaryManager.TreeItemENFRTestInfo, new RecordItemIndex(43));
            repo.SYSTRANDictionaryManager.TreeItemENFRTest.Click("69;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.PushButton' at 11;10.", repo.SYSTRANDictionaryManager.PushButtonInfo, new RecordItemIndex(44));
            repo.SYSTRANDictionaryManager.PushButton.Click("11;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmDictionaryDelete.ButtonYes' at 54;13.", repo.ConfirmDictionaryDelete.ButtonYesInfo, new RecordItemIndex(45));
            repo.ConfirmDictionaryDelete.ButtonYes.Click("54;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
