///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DoubleClickOnTM recording.
    /// </summary>
    [TestModule("3c8a6396-d7a2-46c6-a6b3-5cccd7ba6e5f", ModuleType.Recording, 1)]
    public partial class DoubleClickOnTM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static DoubleClickOnTM instance = new DoubleClickOnTM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DoubleClickOnTM()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DoubleClickOnTM Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemories' at 11;8.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemoriesInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemories.Click("11;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTM' at 70;5.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTMInfo, new RecordItemIndex(1));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTM.Click("70;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTM' at 70;5.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTMInfo, new RecordItemIndex(2));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRDoNotRemoveTM.DoubleClick("70;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
