///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DuplicateEntryDetection recording.
    /// </summary>
    [TestModule("cb4cc75a-1cb7-4626-a93a-8090fa328343", ModuleType.Recording, 1)]
    public partial class DuplicateEntryDetection : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static DuplicateEntryDetection instance = new DuplicateEntryDetection();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DuplicateEntryDetection()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DuplicateEntryDetection Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.File' at 14;11.", repo.SYSTRANDictionaryManager.FileInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.File.Click("14;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.MenuPopup' at 27;9.", repo.SystranDictionaryManager1.MenuPopupInfo, new RecordItemIndex(1));
            repo.SystranDictionaryManager1.MenuPopup.Click("27;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea2' at 37;10.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea2Info, new RecordItemIndex(2));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea2.Click("37;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem2' at 38;3.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem2Info, new RecordItemIndex(3));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem2.Click("38;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea11' at 35;9.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea11Info, new RecordItemIndex(4));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea11.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'DictionaryPropertiesBaseForm.TxtDictName'.", repo.DictionaryPropertiesBaseForm.TxtDictNameInfo, new RecordItemIndex(5));
            repo.DictionaryPropertiesBaseForm.TxtDictName.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.TextEditorEditArea21' at 36;15.", repo.DictionaryPropertiesBaseForm.TextEditorEditArea21Info, new RecordItemIndex(6));
            repo.DictionaryPropertiesBaseForm.TextEditorEditArea21.Click("36;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'DictionaryPropertiesBaseForm.TxtAuthor'.", repo.DictionaryPropertiesBaseForm.TxtAuthorInfo, new RecordItemIndex(7));
            repo.DictionaryPropertiesBaseForm.TxtAuthor.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3' at 10;8.", repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3Info, new RecordItemIndex(8));
            repo.DictionaryPropertiesBaseForm.ButtonEditorDropdownButton3.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.ListItemValuelistValueListItem0' at 116;6.", repo.SystranDictionaryManager1.ListItemValuelistValueListItem0Info, new RecordItemIndex(9));
            repo.SystranDictionaryManager1.ListItemValuelistValueListItem0.Click("116;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DictionaryPropertiesBaseForm.ButtonOK' at 13;10.", repo.DictionaryPropertiesBaseForm.ButtonOKInfo, new RecordItemIndex(10));
            repo.DictionaryPropertiesBaseForm.ButtonOK.Click("13;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage' at 64;11.", repo.SYSTRANDictionaryManager.EnglishSourceLanguageInfo, new RecordItemIndex(11));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage.Click("64;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(12));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage' at 38;11.", repo.SYSTRANDictionaryManager.FrenchTargetLanguageInfo, new RecordItemIndex(13));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage.Click("38;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hi' with focus on 'SYSTRANDictionaryManager.Row0'.", repo.SYSTRANDictionaryManager.Row0Info, new RecordItemIndex(14));
            repo.SYSTRANDictionaryManager.Row0.PressKeys("hi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.CellID' at 19;15.", repo.SYSTRANDictionaryManager.CellIDInfo, new RecordItemIndex(15));
            repo.SYSTRANDictionaryManager.CellID.Click("19;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage1' at 44;12.", repo.SYSTRANDictionaryManager.EnglishSourceLanguage1Info, new RecordItemIndex(16));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage1.Click("44;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello' with focus on 'SYSTRANDictionaryManager.Row1'.", repo.SYSTRANDictionaryManager.Row1Info, new RecordItemIndex(17));
            repo.SYSTRANDictionaryManager.Row1.PressKeys("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage1' at 45;7.", repo.SYSTRANDictionaryManager.FrenchTargetLanguage1Info, new RecordItemIndex(18));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage1.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bonjour' with focus on 'SYSTRANDictionaryManager.Row1'.", repo.SYSTRANDictionaryManager.Row1Info, new RecordItemIndex(19));
            repo.SYSTRANDictionaryManager.Row1.PressKeys("bonjour");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.CellID' at 8;6.", repo.SYSTRANDictionaryManager.CellIDInfo, new RecordItemIndex(20));
            repo.SYSTRANDictionaryManager.CellID.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage2' at 29;9.", repo.SYSTRANDictionaryManager.EnglishSourceLanguage2Info, new RecordItemIndex(21));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage2.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'him' with focus on 'SYSTRANDictionaryManager.Row2'.", repo.SYSTRANDictionaryManager.Row2Info, new RecordItemIndex(22));
            repo.SYSTRANDictionaryManager.Row2.PressKeys("him");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage2' at 33;15.", repo.SYSTRANDictionaryManager.FrenchTargetLanguage2Info, new RecordItemIndex(23));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage2.Click("33;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lui' with focus on 'SYSTRANDictionaryManager.Row2'.", repo.SYSTRANDictionaryManager.Row2Info, new RecordItemIndex(24));
            repo.SYSTRANDictionaryManager.Row2.PressKeys("lui");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.CellID' at 13;8.", repo.SYSTRANDictionaryManager.CellIDInfo, new RecordItemIndex(25));
            repo.SYSTRANDictionaryManager.CellID.Click("13;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage3' at 32;10.", repo.SYSTRANDictionaryManager.EnglishSourceLanguage3Info, new RecordItemIndex(26));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage3.Click("32;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'him' with focus on 'SYSTRANDictionaryManager.Row3'.", repo.SYSTRANDictionaryManager.Row3Info, new RecordItemIndex(27));
            repo.SYSTRANDictionaryManager.Row3.PressKeys("him");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage3' at 32;13.", repo.SYSTRANDictionaryManager.FrenchTargetLanguage3Info, new RecordItemIndex(28));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage3.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lui' with focus on 'SYSTRANDictionaryManager.Row3'.", repo.SYSTRANDictionaryManager.Row3Info, new RecordItemIndex(29));
            repo.SYSTRANDictionaryManager.Row3.PressKeys("lui");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.CellID' at 9;5.", repo.SYSTRANDictionaryManager.CellIDInfo, new RecordItemIndex(30));
            repo.SYSTRANDictionaryManager.CellID.Click("9;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage4' at 34;10.", repo.SYSTRANDictionaryManager.EnglishSourceLanguage4Info, new RecordItemIndex(31));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage4.Click("34;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'I' with focus on 'SYSTRANDictionaryManager.Row4'.", repo.SYSTRANDictionaryManager.Row4Info, new RecordItemIndex(32));
            repo.SYSTRANDictionaryManager.Row4.PressKeys("I");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage4' at 48;13.", repo.SYSTRANDictionaryManager.FrenchTargetLanguage4Info, new RecordItemIndex(33));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage4.Click("48;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Je' with focus on 'SYSTRANDictionaryManager.Row4'.", repo.SYSTRANDictionaryManager.Row4Info, new RecordItemIndex(34));
            repo.SYSTRANDictionaryManager.Row4.PressKeys("Je");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.CellID' at 18;4.", repo.SYSTRANDictionaryManager.CellIDInfo, new RecordItemIndex(35));
            repo.SYSTRANDictionaryManager.CellID.Click("18;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.EnglishSourceLanguage5' at 40;11.", repo.SYSTRANDictionaryManager.EnglishSourceLanguage5Info, new RecordItemIndex(36));
            repo.SYSTRANDictionaryManager.EnglishSourceLanguage5.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'me' with focus on 'SYSTRANDictionaryManager.Text'.", repo.SYSTRANDictionaryManager.TextInfo, new RecordItemIndex(37));
            repo.SYSTRANDictionaryManager.Text.PressKeys("me");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.FrenchTargetLanguage5' at 40;11.", repo.SYSTRANDictionaryManager.FrenchTargetLanguage5Info, new RecordItemIndex(38));
            repo.SYSTRANDictionaryManager.FrenchTargetLanguage5.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Je' with focus on 'SYSTRANDictionaryManager.Row5'.", repo.SYSTRANDictionaryManager.Row5Info, new RecordItemIndex(39));
            repo.SYSTRANDictionaryManager.Row5.PressKeys("Je");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.Save' at 10;8.", repo.SYSTRANDictionaryManager.SaveInfo, new RecordItemIndex(40));
            repo.SYSTRANDictionaryManager.Save.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.Edit' at 23;9.", repo.SYSTRANDictionaryManager.EditInfo, new RecordItemIndex(41));
            repo.SYSTRANDictionaryManager.Edit.Click("23;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystranDictionaryManager1.MenuPopup' at 50;245.", repo.SystranDictionaryManager1.MenuPopupInfo, new RecordItemIndex(42));
            repo.SystranDictionaryManager1.MenuPopup.Click("50;245");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.French' at 6;6.", repo.FloatingWindowContainer.FrenchInfo, new RecordItemIndex(43));
            repo.FloatingWindowContainer.French.Click("6;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.French' at 6;4.", repo.FloatingWindowContainer.FrenchInfo, new RecordItemIndex(44));
            repo.FloatingWindowContainer.French.Click("6;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.Find' at 27;8.", repo.FloatingWindowContainer.FindInfo, new RecordItemIndex(45));
            repo.FloatingWindowContainer.Find.Click("27;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'SYSTRANDictionaryManager.Count'.", repo.SYSTRANDictionaryManager.CountInfo, new RecordItemIndex(46));
            Validate.Attribute(repo.SYSTRANDictionaryManager.CountInfo, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.English' at 8;5.", repo.FloatingWindowContainer.EnglishInfo, new RecordItemIndex(47));
            repo.FloatingWindowContainer.English.Click("8;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.French' at 8;6.", repo.FloatingWindowContainer.FrenchInfo, new RecordItemIndex(48));
            repo.FloatingWindowContainer.French.Click("8;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.French' at 11;5.", repo.FloatingWindowContainer.FrenchInfo, new RecordItemIndex(49));
            repo.FloatingWindowContainer.French.Click("11;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.Find' at 20;9.", repo.FloatingWindowContainer.FindInfo, new RecordItemIndex(50));
            repo.FloatingWindowContainer.Find.Click("20;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'SYSTRANDictionaryManager.Count1'.", repo.SYSTRANDictionaryManager.Count1Info, new RecordItemIndex(51));
            Validate.Attribute(repo.SYSTRANDictionaryManager.Count1Info, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.English' at 8;7.", repo.FloatingWindowContainer.EnglishInfo, new RecordItemIndex(52));
            repo.FloatingWindowContainer.English.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.English' at 8;7.", repo.FloatingWindowContainer.EnglishInfo, new RecordItemIndex(53));
            repo.FloatingWindowContainer.English.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.Find' at 44;12.", repo.FloatingWindowContainer.FindInfo, new RecordItemIndex(54));
            repo.FloatingWindowContainer.Find.Click("44;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'SYSTRANDictionaryManager.Count2'.", repo.SYSTRANDictionaryManager.Count2Info, new RecordItemIndex(55));
            Validate.Attribute(repo.SYSTRANDictionaryManager.Count2Info, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'SYSTRANDictionaryManager.Count1'.", repo.SYSTRANDictionaryManager.Count1Info, new RecordItemIndex(56));
            Validate.Attribute(repo.SYSTRANDictionaryManager.Count1Info, "Text", "2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FloatingWindowContainer.DockableWindow' at 462;9.", repo.FloatingWindowContainer.DockableWindowInfo, new RecordItemIndex(57));
            repo.FloatingWindowContainer.DockableWindow.Click("462;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.UserDictionaries1' at 11;6.", repo.SYSTRANDictionaryManager.SdmWindowOpen.UserDictionaries1Info, new RecordItemIndex(58));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.UserDictionaries1.Click("11;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRTest' at 69;8.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRTestInfo, new RecordItemIndex(59));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRTest.Click("69;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.PushButton' at 11;10.", repo.SYSTRANDictionaryManager.PushButtonInfo, new RecordItemIndex(60));
            repo.SYSTRANDictionaryManager.PushButton.Click("11;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmDictionaryDelete.ButtonYes' at 54;13.", repo.ConfirmDictionaryDelete.ButtonYesInfo, new RecordItemIndex(61));
            repo.ConfirmDictionaryDelete.ButtonYes.Click("54;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
