///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace helloproj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatePublishTranslationMemory recording.
    /// </summary>
    [TestModule("c09f2e3c-7859-44e2-8952-289d6fad38d3", ModuleType.Recording, 1)]
    public partial class ValidatePublishTranslationMemory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidatePublishTranslationMemory instance = new ValidatePublishTranslationMemory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatePublishTranslationMemory()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatePublishTranslationMemory Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemories' at 9;6.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemoriesInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TranslationMemories.Click("9;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='[EN-FR] hello') on item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1'.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info, new RecordItemIndex(1));
            Validate.Attribute(repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info, "Text", "[EN-FR] hello");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=110,Height=16}) on item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1'.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info, new RecordItemIndex(2));
            Validate.ContainsImage(repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info, TreeItemENFRHello1_Screenshot1, TreeItemENFRHello1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1' at 48;6.", repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info, new RecordItemIndex(3));
            repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1.Click("48;6");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage TreeItemENFRHello1_Screenshot1
        { get { return repo.SYSTRANDictionaryManager.SdmWindowOpen.TreeItemENFRHello1Info.GetScreenshot1(new Rectangle(0, 0, 110, 16)); } }

        Imaging.FindOptions TreeItemENFRHello1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
