///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TypeFileNameAndLocationForExportTMInTXTFormat recording.
    /// </summary>
    [TestModule("0de1ab73-9a13-4df1-b69a-09fffacda0c3", ModuleType.Recording, 1)]
    public partial class TypeFileNameAndLocationForExportTMInTXTFormat : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static TypeFileNameAndLocationForExportTMInTXTFormat instance = new TypeFileNameAndLocationForExportTMInTXTFormat();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TypeFileNameAndLocationForExportTMInTXTFormat()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TypeFileNameAndLocationForExportTMInTXTFormat Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserDict.Text1001' at 219;5.", repo.UserDict.Text1001Info, new RecordItemIndex(0));
            repo.UserDict.Text1001.Click("219;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\Users\\pandey\\Documents\\Ranorex\\RanorexStudio Projects\\testtooltip\\DictionaryManager\\ExportDictionaries\\ExportTXTTranslationMemory' with focus on 'UserDict.Text1001'.", repo.UserDict.Text1001Info, new RecordItemIndex(1));
            repo.UserDict.Text1001.PressKeys("C:\\Users\\pandey\\Documents\\Ranorex\\RanorexStudio Projects\\testtooltip\\DictionaryManager\\ExportDictionaries\\ExportTXTTranslationMemory");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserDict.ComboBox' at 8;11.", repo.UserDict.ComboBoxInfo, new RecordItemIndex(2));
            repo.UserDict.ComboBox.Click("8;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'dropdownListToSelectFormat.SelectTXTFormat' at 346;10.", repo.dropdownListToSelectFormat.SelectTXTFormatInfo, new RecordItemIndex(3));
            repo.dropdownListToSelectFormat.SelectTXTFormat.Click("346;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserDict.ButtonSave' at 63;9.", repo.UserDict.ButtonSaveInfo, new RecordItemIndex(4));
            repo.UserDict.ButtonSave.Click("63;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
