///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateANormalizedDictionary recording.
    /// </summary>
    [TestModule("4ecd6f84-390f-4f59-abe8-e5d91e0f6521", ModuleType.Recording, 1)]
    public partial class ValidateANormalizedDictionary : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateANormalizedDictionary instance = new ValidateANormalizedDictionary();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateANormalizedDictionary()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateANormalizedDictionary Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='[EN] UserNormalization') on item 'SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalization'.", repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalizationInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalizationInfo, "Text", "[EN] UserNormalization");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Normalization') on item 'SYSTRANDictionaryManager.ValidateNormalization.Normalization'.", repo.SYSTRANDictionaryManager.ValidateNormalization.NormalizationInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateNormalization.NormalizationInfo, "Text", "Normalization");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sujit') on item 'SYSTRANDictionaryManager.ValidateUserDictionary.Sujit'.", repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, "Text", "Sujit");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
