///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateATranslationMemory recording.
    /// </summary>
    [TestModule("c0390f4b-d9be-458a-97d9-65913c987bec", ModuleType.Recording, 1)]
    public partial class ValidateATranslationMemory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateATranslationMemory instance = new ValidateATranslationMemory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateATranslationMemory()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateATranslationMemory Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='[EN-FR] UserTranslationMemory') on item 'SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRTranslationMemory'.", repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRTranslationMemoryInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRTranslationMemoryInfo, "Text", "[EN-FR] UserTranslationMemory");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sujit') on item 'SYSTRANDictionaryManager.ValidateUserDictionary.Sujit'.", repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, "Text", "Sujit");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Translation Memories') on item 'SYSTRANDictionaryManager.ValidateTranslationMemory.TranslationMemories'.", repo.SYSTRANDictionaryManager.ValidateTranslationMemory.TranslationMemoriesInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateTranslationMemory.TranslationMemoriesInfo, "Text", "Translation Memories");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
