///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateAUserDictionary recording.
    /// </summary>
    [TestModule("10e7f795-d6de-466c-8f09-468ca2ad719c", ModuleType.Recording, 1)]
    public partial class ValidateAUserDictionary : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateAUserDictionary instance = new ValidateAUserDictionary();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateAUserDictionary()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateAUserDictionary Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='[EN-FR] UserDict') on item 'SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRUserDictionary'.", repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRUserDictionaryInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.ENFRUserDictionaryInfo, "Text", "[EN-FR] UserDict");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='User Dictionaries') on item 'SYSTRANDictionaryManager.ValidateUserDictionary.UserDictionaries'.", repo.SYSTRANDictionaryManager.ValidateUserDictionary.UserDictionariesInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateUserDictionary.UserDictionariesInfo, "Text", "User Dictionaries");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Sujit') on item 'SYSTRANDictionaryManager.ValidateUserDictionary.Sujit'.", repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateUserDictionary.SujitInfo, "Text", "Sujit");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
