///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateAddEntryOnUserDictionary recording.
    /// </summary>
    [TestModule("c4f589ca-9541-48d3-9fc7-655e15b7e039", ModuleType.Recording, 1)]
    public partial class ValidateAddEntryOnUserDictionary : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateAddEntryOnUserDictionary instance = new ValidateAddEntryOnUserDictionary();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateAddEntryOnUserDictionary()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateAddEntryOnUserDictionary Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.Text1'.", repo.SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.Text1Info, new RecordItemIndex(0));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.Text1Info, "Text", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Number of entries: 1') on item 'SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.NumberOfEntries1'.", repo.SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.NumberOfEntries1Info, new RecordItemIndex(1));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateAddEntryUserDictionary.NumberOfEntries1Info, "AccessibleName", "Number of entries: 1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
