///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateConfidenceIntervalOfAnEntryInNormalization recording.
    /// </summary>
    [TestModule("8d5d8d6d-a12b-4387-994c-970b761db98a", ModuleType.Recording, 1)]
    public partial class ValidateConfidenceIntervalOfAnEntryInNormalization : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateConfidenceIntervalOfAnEntryInNormalization instance = new ValidateConfidenceIntervalOfAnEntryInNormalization();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateConfidenceIntervalOfAnEntryInNormalization()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateConfidenceIntervalOfAnEntryInNormalization Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalization' at Center.", repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalizationInfo, new RecordItemIndex(0));
            repo.SYSTRANDictionaryManager.OpenDictionary.DictionariesName.TreeItemENUserNormalization.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'SYSTRANDictionaryManager.ValidateConfidenceInUserDictionary.Confidence' at 49;12.", repo.SYSTRANDictionaryManager.ValidateConfidenceInUserDictionary.ConfidenceInfo, new RecordItemIndex(1));
            repo.SYSTRANDictionaryManager.ValidateConfidenceInUserDictionary.Confidence.MoveTo("49;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='60%') on item 'toolTip.ToolTip60Percent'.", repo.toolTip.ToolTip60Percent.SelfInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.toolTip.ToolTip60Percent.SelfInfo, "Text", "60%");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
