///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DictionaryManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDoNotTranslateInUserDictionaryEntry recording.
    /// </summary>
    [TestModule("68e2711a-ba46-4687-97f1-e7ffc96b5cdf", ModuleType.Recording, 1)]
    public partial class ValidateDoNotTranslateInUserDictionaryEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DictionaryManagerRepository repository.
        /// </summary>
        public static DictionaryManagerRepository repo = DictionaryManagerRepository.Instance;

        static ValidateDoNotTranslateInUserDictionaryEntry instance = new ValidateDoNotTranslateInUserDictionaryEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDoNotTranslateInUserDictionaryEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDoNotTranslateInUserDictionaryEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguage'.", repo.SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguageInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguageInfo, "Text", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'DoNotTranslateImage' with region {X=0,Y=0,Width=119,Height=24}) on item 'SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguage'.", repo.SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguageInfo, new RecordItemIndex(1));
            Validate.ContainsImage(repo.SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguageInfo, FrenchTargetLanguage_DoNotTranslateImage, FrenchTargetLanguage_DoNotTranslateImage_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage FrenchTargetLanguage_DoNotTranslateImage
        { get { return repo.SYSTRANDictionaryManager.ValidateAddEntryTranslationMemory.FrenchTargetLanguageInfo.GetDoNotTranslateImage(new Rectangle(0, 0, 119, 24)); } }

        Imaging.FindOptions FrenchTargetLanguage_DoNotTranslateImage_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
