///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace testtooltip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClearInputText recording.
    /// </summary>
    [TestModule("2120b3bf-e61c-4c1c-bed9-610991bf6df0", ModuleType.Recording, 1)]
    public partial class ClearInputText : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testtooltipRepository repository.
        /// </summary>
        public static testtooltipRepository repo = testtooltipRepository.Instance;

        static ClearInputText instance = new ClearInputText();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClearInputText()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClearInputText Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1' at 86;21.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1Info, new RecordItemIndex(0));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1.Click("86;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hello'.", new RecordItemIndex(1));
            Keyboard.Press("Hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background2' at 24;31.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background2Info, new RecordItemIndex(2));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background2.Click("24;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background5' at 15;18.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background5Info, new RecordItemIndex(4));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background5.Click("15;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotContains (Text!>'Hello') on item 'SYSTRANInteractiveTranslator.MSrcRichTextBox'.", repo.SYSTRANInteractiveTranslator.MSrcRichTextBoxInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.SYSTRANInteractiveTranslator.MSrcRichTextBoxInfo, "Text", new Regex("^((?!("+Regex.Escape("Hello")+"))(.|\n))*$"));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
