///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace testtooltip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CopyandPasteBycommandline recording.
    /// </summary>
    [TestModule("6f2653e3-3bde-40e7-a33b-232dfec99d6b", ModuleType.Recording, 1)]
    public partial class CopyandPasteBycommandline : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testtooltipRepository repository.
        /// </summary>
        public static testtooltipRepository repo = testtooltipRepository.Instance;

        static CopyandPasteBycommandline instance = new CopyandPasteBycommandline();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CopyandPasteBycommandline()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CopyandPasteBycommandline Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1' at 193;65.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1Info, new RecordItemIndex(0));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement1.Click("193;65");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hello'.", new RecordItemIndex(1));
            Keyboard.Press("hello");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background2' at 29;30.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background2Info, new RecordItemIndex(2));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background2.Click("29;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4' at 11;9.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4Info, new RecordItemIndex(3));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4.Click("11;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement6' at 328;62.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement6Info, new RecordItemIndex(4));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement6.Click("328;62");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}H{LShiftKey up}i{Space}'.", new RecordItemIndex(5));
            Keyboard.Press("{LShiftKey down}H{LShiftKey up}i{Space}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}I{LShiftKey up}{Space}am{Space}sujit'.", new RecordItemIndex(6));
            Keyboard.Press("{LShiftKey down}I{LShiftKey up}{Space}am{Space}sujit");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement3' at 10;8.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement3Info, new RecordItemIndex(7));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement3.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRAN.Cancel' at 61;10.", repo.SYSTRAN.CancelInfo, new RecordItemIndex(8));
            repo.SYSTRAN.Cancel.Click("61;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4' at 13;5.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4Info, new RecordItemIndex(9));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement4.Click("13;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background1' at 20;15.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background1Info, new RecordItemIndex(10));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background1.Click("20;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5' at 39;12.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5Info, new RecordItemIndex(11));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5.MoveTo("39;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5' at 47;4.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5Info, new RecordItemIndex(12));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomeElement5.MoveTo("47;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Explorer.List1' at 574;315.", repo.Explorer.List1Info, new RecordItemIndex(13));
            repo.Explorer.List1.MoveTo("574;315");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}'.", new RecordItemIndex(14));
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+V' Press.", new RecordItemIndex(15));
            Keyboard.Press(System.Windows.Forms.Keys.V | System.Windows.Forms.Keys.Control, 47, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SYSTRANInteractiveTranslator1.SomeElement' at 5;7.", repo.SYSTRANInteractiveTranslator1.SomeElementInfo, new RecordItemIndex(16));
            repo.SYSTRANInteractiveTranslator1.SomeElement.MoveTo("5;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SYSTRANInteractiveTranslator1.SomeElement' at 5;7.", repo.SYSTRANInteractiveTranslator1.SomeElementInfo, new RecordItemIndex(17));
            repo.SYSTRANInteractiveTranslator1.SomeElement.MoveTo("5;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
