///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace testtooltip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The selectProfileFrEn recording.
    /// </summary>
    [TestModule("f7efb5c8-04f1-4e4a-8640-31495d9209bb", ModuleType.Recording, 1)]
    public partial class SelectProfileFrEn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testtooltipRepository repository.
        /// </summary>
        public static testtooltipRepository repo = testtooltipRepository.Instance;

        static SelectProfileFrEn instance = new SelectProfileFrEn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectProfileFrEn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectProfileFrEn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background4' at 97;19.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info, new RecordItemIndex(0));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4.Click("97;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator2.SomeContainer.French' at 38;12.", repo.SYSTRANInteractiveTranslator2.SomeContainer.FrenchInfo, new RecordItemIndex(1));
            repo.SYSTRANInteractiveTranslator2.SomeContainer.French.Click("38;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1' at 2;2.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1Info, new RecordItemIndex(2));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1.Click("2;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator2.SomeContainer.TranslatorFrEn' at 57;5.", repo.SYSTRANInteractiveTranslator2.SomeContainer.TranslatorFrEnInfo, new RecordItemIndex(3));
            repo.SYSTRANInteractiveTranslator2.SomeContainer.TranslatorFrEn.Click("57;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
