///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace testtooltip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SwitchLanguagesInSIT recording.
    /// </summary>
    [TestModule("55cb846f-5e08-4703-acc3-b7a1acc63f9b", ModuleType.Recording, 1)]
    public partial class SwitchLanguagesInSIT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the testtooltipRepository repository.
        /// </summary>
        public static testtooltipRepository repo = testtooltipRepository.Instance;

        static SwitchLanguagesInSIT instance = new SwitchLanguagesInSIT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SwitchLanguagesInSIT()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SwitchLanguagesInSIT Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(0));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=110,Height=27}) on item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background4'.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info, new RecordItemIndex(1));
            Validate.ContainsImage(repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info, Background4_Screenshot1, Background4_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background3'.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background3Info, new RecordItemIndex(2));
            Validate.Exists(repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background3Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.SomePicture2' at 6;11.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomePicture2Info, new RecordItemIndex(3));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.SomePicture2.Click("6;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=110,Height=27}) on item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background4'.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info, new RecordItemIndex(4));
            Validate.ContainsImage(repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info, Background4_Screenshot2, Background4_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=110,Height=27}) on item 'SYSTRANInteractiveTranslator1.SomeContainer1.Background3'.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background3Info, new RecordItemIndex(5));
            Validate.ContainsImage(repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background3Info, Background3_Screenshot1, Background3_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow' at 5;4.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrowInfo, new RecordItemIndex(7));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow.Click("5;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator2.SomeContainer.English1' at 61;1.", repo.SYSTRANInteractiveTranslator2.SomeContainer.English1Info, new RecordItemIndex(8));
            repo.SYSTRANInteractiveTranslator2.SomeContainer.English1.Click("61;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1' at 2;2.", repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1Info, new RecordItemIndex(9));
            repo.SYSTRANInteractiveTranslator1.SomeContainer1.BtnArrow1.Click("2;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANInteractiveTranslator2.SomeContainer.DoNotRemoveUserProfileWIthTMAndUse' at 118;4.", repo.SYSTRANInteractiveTranslator2.SomeContainer.DoNotRemoveUserProfileWIthTMAndUseInfo, new RecordItemIndex(10));
            repo.SYSTRANInteractiveTranslator2.SomeContainer.DoNotRemoveUserProfileWIthTMAndUse.Click("118;4");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage Background4_Screenshot1
        { get { return repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info.GetScreenshot1(new Rectangle(0, 0, 110, 27)); } }

        Imaging.FindOptions Background4_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Background4_Screenshot2
        { get { return repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background4Info.GetScreenshot2(new Rectangle(0, 0, 110, 27)); } }

        Imaging.FindOptions Background4_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Background3_Screenshot1
        { get { return repo.SYSTRANInteractiveTranslator1.SomeContainer1.Background3Info.GetScreenshot1(new Rectangle(0, 0, 110, 27)); } }

        Imaging.FindOptions Background3_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
