///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LanguageManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LanguageManagerRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("f799ee33-a5fc-4d12-a32c-afa8e13029ab")]
    public partial class LanguageManagerRepository : RepoGenBaseFolder
    {
        static LanguageManagerRepository instance = new LanguageManagerRepository();
        LanguageManagerRepositoryFolders.SYSTRANLanguageManagerAppFolder _systranlanguagemanager;
        LanguageManagerRepositoryFolders.DellOfficialSiteThePowerToDoMorAppFolder _dellofficialsitethepowertodomor;
        LanguageManagerRepositoryFolders.SYSTRANLanguageManager1AppFolder _systranlanguagemanager1;
        LanguageManagerRepositoryFolders.TranslationResourcesAppFolder _translationresources;
        LanguageManagerRepositoryFolders.ExplorerAppFolder _explorer;
        LanguageManagerRepositoryFolders.SYSTRANQuickFileTranslatorAppFolder _systranquickfiletranslator;
        LanguageManagerRepositoryFolders.AbortTranslationAppFolder _aborttranslation;

        /// <summary>
        /// Gets the singleton class instance representing the LanguageManagerRepository element repository.
        /// </summary>
        [RepositoryFolder("f799ee33-a5fc-4d12-a32c-afa8e13029ab")]
        public static LanguageManagerRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LanguageManagerRepository() 
            : base("LanguageManagerRepository", "/", null, 0, false, "f799ee33-a5fc-4d12-a32c-afa8e13029ab", ".\\RepositoryImages\\LanguageManagerRepositoryf799ee33.rximgres")
        {
            _systranlanguagemanager = new LanguageManagerRepositoryFolders.SYSTRANLanguageManagerAppFolder(this);
            _dellofficialsitethepowertodomor = new LanguageManagerRepositoryFolders.DellOfficialSiteThePowerToDoMorAppFolder(this);
            _systranlanguagemanager1 = new LanguageManagerRepositoryFolders.SYSTRANLanguageManager1AppFolder(this);
            _translationresources = new LanguageManagerRepositoryFolders.TranslationResourcesAppFolder(this);
            _explorer = new LanguageManagerRepositoryFolders.ExplorerAppFolder(this);
            _systranquickfiletranslator = new LanguageManagerRepositoryFolders.SYSTRANQuickFileTranslatorAppFolder(this);
            _aborttranslation = new LanguageManagerRepositoryFolders.AbortTranslationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f799ee33-a5fc-4d12-a32c-afa8e13029ab")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SYSTRANLanguageManager folder.
        /// </summary>
        [RepositoryFolder("4c289af1-9f6c-43aa-915d-3957017e5399")]
        public virtual LanguageManagerRepositoryFolders.SYSTRANLanguageManagerAppFolder SYSTRANLanguageManager
        {
            get { return _systranlanguagemanager; }
        }

        /// <summary>
        /// The DellOfficialSiteThePowerToDoMor folder.
        /// </summary>
        [RepositoryFolder("5210798d-e2d9-43c8-8341-d64747302fbe")]
        public virtual LanguageManagerRepositoryFolders.DellOfficialSiteThePowerToDoMorAppFolder DellOfficialSiteThePowerToDoMor
        {
            get { return _dellofficialsitethepowertodomor; }
        }

        /// <summary>
        /// The SYSTRANLanguageManager1 folder.
        /// </summary>
        [RepositoryFolder("0b282e6c-ae7f-4b08-bb24-4e6b3249eb04")]
        public virtual LanguageManagerRepositoryFolders.SYSTRANLanguageManager1AppFolder SYSTRANLanguageManager1
        {
            get { return _systranlanguagemanager1; }
        }

        /// <summary>
        /// The TranslationResources folder.
        /// </summary>
        [RepositoryFolder("25b51433-0345-4a65-b956-e8d92dfa5fd3")]
        public virtual LanguageManagerRepositoryFolders.TranslationResourcesAppFolder TranslationResources
        {
            get { return _translationresources; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("096128c6-696a-4ade-9851-1e797c26b364")]
        public virtual LanguageManagerRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The SYSTRANQuickFileTranslator folder.
        /// </summary>
        [RepositoryFolder("e9c42457-a977-4a67-988a-783a8b97d7d3")]
        public virtual LanguageManagerRepositoryFolders.SYSTRANQuickFileTranslatorAppFolder SYSTRANQuickFileTranslator
        {
            get { return _systranquickfiletranslator; }
        }

        /// <summary>
        /// The AbortTranslation folder.
        /// </summary>
        [RepositoryFolder("7a26042b-2fcd-4ff8-a3f4-09932e50163e")]
        public virtual LanguageManagerRepositoryFolders.AbortTranslationAppFolder AbortTranslation
        {
            get { return _aborttranslation; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class LanguageManagerRepositoryFolders
    {
        /// <summary>
        /// The SYSTRANLanguageManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c289af1-9f6c-43aa-915d-3957017e5399")]
        public partial class SYSTRANLanguageManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systranstoreInfo;

            /// <summary>
            /// Creates a new SYSTRANLanguageManager  folder.
            /// </summary>
            public SYSTRANLanguageManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANLanguageManager", "/form[@title='SYSTRAN Language Manager']", parentFolder, 30000, null, true, "4c289af1-9f6c-43aa-915d-3957017e5399", "")
            {
                _systranstoreInfo = new RepoItemInfo(this, "SYSTRANStore", "?/?/container[@accessiblename='SYSTRAN Language Manager']/?/?/link[@accessiblename='SYSTRAN Store']/text[@accessiblename='SYSTRAN Store']", 30000, null, "c30db001-120e-4183-9239-167246d8d998");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c289af1-9f6c-43aa-915d-3957017e5399")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c289af1-9f6c-43aa-915d-3957017e5399")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SYSTRANStore item.
            /// </summary>
            [RepositoryItem("c30db001-120e-4183-9239-167246d8d998")]
            public virtual Ranorex.Text SYSTRANStore
            {
                get
                {
                    return _systranstoreInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SYSTRANStore item info.
            /// </summary>
            [RepositoryItemInfo("c30db001-120e-4183-9239-167246d8d998")]
            public virtual RepoItemInfo SYSTRANStoreInfo
            {
                get
                {
                    return _systranstoreInfo;
                }
            }
        }

        /// <summary>
        /// The DellOfficialSiteThePowerToDoMorAppFolder folder.
        /// </summary>
        [RepositoryFolder("5210798d-e2d9-43c8-8341-d64747302fbe")]
        public partial class DellOfficialSiteThePowerToDoMorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editInfo;

            /// <summary>
            /// Creates a new DellOfficialSiteThePowerToDoMor  folder.
            /// </summary>
            public DellOfficialSiteThePowerToDoMorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DellOfficialSiteThePowerToDoMor", "/form[@title~'^Dell\\ Official\\ Site\\ -\\ The\\ ']", parentFolder, 30000, null, true, "5210798d-e2d9-43c8-8341-d64747302fbe", "")
            {
                _editInfo = new RepoItemInfo(this, "Edit", "?/?/form[@controlid='40966']/?/?/text[@class='Edit']", 30000, null, "c7430e8b-09e2-4c39-b80f-3a411a192bea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5210798d-e2d9-43c8-8341-d64747302fbe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5210798d-e2d9-43c8-8341-d64747302fbe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("c7430e8b-09e2-4c39-b80f-3a411a192bea")]
            public virtual Ranorex.Text Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("c7430e8b-09e2-4c39-b80f-3a411a192bea")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRANLanguageManager1AppFolder folder.
        /// </summary>
        [RepositoryFolder("0b282e6c-ae7f-4b08-bb24-4e6b3249eb04")]
        public partial class SYSTRANLanguageManager1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantagrefreshInfo;
            RepoItemInfo _spantagaddInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _somebtagInfo;
            RepoItemInfo _select2resultlabel3Info;
            RepoItemInfo _somebtag1Info;
            RepoItemInfo _select2resultlabel4Info;
            RepoItemInfo _selectlanguagessubmitInfo;
            RepoItemInfo _inputnewprofilenameInfo;
            RepoItemInfo _inputprofileidInfo;
            RepoItemInfo _checkboxInfo;
            RepoItemInfo _submitaddprofileInfo;
            RepoItemInfo _profilewithtmInfo;
            RepoItemInfo _atagdeleteInfo;
            RepoItemInfo _buttontagokInfo;
            RepoItemInfo _addprofileInfo;
            RepoItemInfo _checkbox1Info;
            RepoItemInfo _profilewithuserdictInfo;
            RepoItemInfo _profilewithuserdictandtmInfo;
            RepoItemInfo _profileidhelpInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _linguisticresourcesInfo;
            RepoItemInfo _dictionariesInfo;
            RepoItemInfo _dictionaries1Info;
            RepoItemInfo _normalizationsInfo;
            RepoItemInfo _normalizations1Info;
            RepoItemInfo _licensesInfo;
            RepoItemInfo _licenses1Info;
            RepoItemInfo _addproductkeybuttonInfo;
            RepoItemInfo _addaproductkeyInfo;
            RepoItemInfo _close1Info;
            RepoItemInfo _submitaddproductkeyInfo;
            RepoItemInfo _select2resultlabel5Info;

            /// <summary>
            /// Creates a new SYSTRANLanguageManager1  folder.
            /// </summary>
            public SYSTRANLanguageManager1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANLanguageManager1", "/dom[@domain='localhost:3500']", parentFolder, 30000, null, false, "0b282e6c-ae7f-4b08-bb24-4e6b3249eb04", "")
            {
                _spantagrefreshInfo = new RepoItemInfo(this, "SpanTagRefresh", ".//button[#'refreshProfile']/span[@innertext=' Refresh']", 30000, null, "56e65335-aba5-40f2-9444-10af6046c690");
                _spantagaddInfo = new RepoItemInfo(this, "SpanTagAdd", ".//button[#'addProfile']/span[@innertext=' Add']", 30000, null, "70a944cc-7e51-4463-8a21-3a2f857a2300");
                _searchInfo = new RepoItemInfo(this, "Search", ".//div[#'profileTable_filter']/?/?/input[@type='search']", 30000, null, "4efa5b3b-7dbc-4cbe-9ea7-30fc13a241c2");
                _somebtagInfo = new RepoItemInfo(this, "SomeBTag", ".//div[#'s2id_sourceButton']//b", 30000, null, "cdea1b4c-a733-424f-a718-736092f4bb5a");
                _select2resultlabel3Info = new RepoItemInfo(this, "Select2ResultLabel3", ".//div[#'select2-result-label-3']", 30000, null, "218a2c4d-6bc7-4ec4-a7da-038ef3d75d98");
                _somebtag1Info = new RepoItemInfo(this, "SomeBTag1", ".//div[#'s2id_targetButton']//b", 30000, null, "2e9335c0-9a7b-49af-8521-133aaf19ae08");
                _select2resultlabel4Info = new RepoItemInfo(this, "Select2ResultLabel4", ".//div[#'select2-result-label-4']", 30000, null, "1ed1677a-10e8-4657-826e-ce409bbc7509");
                _selectlanguagessubmitInfo = new RepoItemInfo(this, "SelectLanguagesSubmit", ".//button[#'selectLanguagesSubmit']", 30000, null, "ad00f709-79a7-43e5-a56e-3c1f9d92583a");
                _inputnewprofilenameInfo = new RepoItemInfo(this, "InputNewProfileName", ".//input[#'inputNewProfileName']", 30000, null, "41996b51-bb06-4d9a-9108-96b158a89dc5");
                _inputprofileidInfo = new RepoItemInfo(this, "InputProfileId", ".//input[#'inputProfileId']", 30000, null, "a5233ce4-09c0-4c20-9f83-d95406e431f1");
                _checkboxInfo = new RepoItemInfo(this, "Checkbox", ".//div[#'userDictSelection']/div/div[1]/?/?/input[@type='checkbox']", 30000, null, "86865eb5-39bc-48ce-b242-c496704f23c9");
                _submitaddprofileInfo = new RepoItemInfo(this, "SubmitAddProfile", ".//button[#'submitAddProfile']", 30000, null, "5809620f-756c-428e-a8a7-e94d1602b2cd");
                _profilewithtmInfo = new RepoItemInfo(this, "ProfileWithTm", ".//table[#'profileTable']//td[@innertext='profile_with_tm']", 30000, null, "f367118d-53f5-4d6c-9bb6-e9ef0c505170");
                _atagdeleteInfo = new RepoItemInfo(this, "ATagDelete", ".//table[#'profileTable']/tbody/tr[1]/td[7]/a[@innertext=' Delete']", 30000, null, "ecf75698-1543-4786-9cd0-30cd8c458142");
                _buttontagokInfo = new RepoItemInfo(this, "ButtonTagOK", "body/div[9]/div/div/div[2]/button[@innertext='OK']", 30000, null, "c97e462e-5c98-4605-ae45-207a424b31c0");
                _addprofileInfo = new RepoItemInfo(this, "AddProfile", ".//button[#'addProfile']", 30000, null, "634149ab-f447-4fb7-b4ff-444b918e5c6b");
                _checkbox1Info = new RepoItemInfo(this, "Checkbox1", ".//div[#'userDictSelection']/div/div[2]/?/?/input[@type='checkbox']", 30000, null, "23fc9158-02ac-4b19-ad36-6f8ccdde1ab9");
                _profilewithuserdictInfo = new RepoItemInfo(this, "ProfileWithUserDict", ".//table[#'profileTable']//td[@innertext='Profile_With_UserDict']", 30000, null, "565c3b9e-a20b-496b-ada8-eb54fe739b50");
                _profilewithuserdictandtmInfo = new RepoItemInfo(this, "ProfileWithUserDictAndTM", ".//table[#'profileTable']//td[@innertext~'^Profile_With_UserDict_And']", 30000, null, "0d32c490-0f99-459a-b461-27254b5aa2c3");
                _profileidhelpInfo = new RepoItemInfo(this, "ProfileIdHelp", ".//span[#'profileIdHelp']", 30000, null, "ec54bb7e-4a5e-4b71-a24e-55271ac27c9c");
                _closeInfo = new RepoItemInfo(this, "Close", ".//div[#'addProfileModal']/div/div/div[3]/button[@innertext='Close']", 30000, null, "8d609d08-bebb-475f-974d-76a56e704c02");
                _linguisticresourcesInfo = new RepoItemInfo(this, "LinguisticResources", ".//li[#'linguisticResourcesNavBar']/a[@innertext='Linguistic Resources']", 30000, null, "dec782c7-0576-4ab4-ad39-38cf6846ff16");
                _dictionariesInfo = new RepoItemInfo(this, "Dictionaries", ".//li[#'linguisticResourcesNavBar']//a[@innertext='Dictionaries']", 30000, null, "c6282c9e-140e-4b75-a2d3-e17acfbf7554");
                _dictionaries1Info = new RepoItemInfo(this, "Dictionaries1", ".//div[#'dictionaryContent']/h3[@innertext='Dictionaries']", 30000, null, "06d122e6-e267-4ee8-bea9-05dd6d41fd11");
                _normalizationsInfo = new RepoItemInfo(this, "Normalizations", ".//li[#'linguisticResourcesNavBar']//a[@innertext='Normalizations']", 30000, null, "e34a084a-e4e1-48fd-9070-f6f308a416ad");
                _normalizations1Info = new RepoItemInfo(this, "Normalizations1", ".//div[#'normalizationContent']/h3[@innertext='Normalizations']", 30000, null, "98eefab4-cf31-4937-b4b1-056701031fd7");
                _licensesInfo = new RepoItemInfo(this, "Licenses", ".//li[#'licencesNavBar']/a[@innertext='Licenses']", 30000, null, "952c2cf0-6c56-4ff3-b545-a9755697937a");
                _licenses1Info = new RepoItemInfo(this, "Licenses1", ".//div[#'licenseContent']/h3[@innertext='Licenses']", 30000, null, "4bd45166-72f7-41ab-9420-b2e9293880c4");
                _addproductkeybuttonInfo = new RepoItemInfo(this, "AddProductKeyButton", ".//button[#'addProductKeyButton']", 30000, null, "e27fb162-ddff-4423-8519-11002a82271c");
                _addaproductkeyInfo = new RepoItemInfo(this, "AddAProductKey", ".//div[#'addProductKeyModal']/div/div/div[1]/h3[@innertext='Add a product key']", 30000, null, "21951eee-db38-4a88-8670-619a0eb87915");
                _close1Info = new RepoItemInfo(this, "Close1", ".//div[#'addProductKeyModal']/div/div/div[3]/button[@innertext='Close']", 30000, null, "cffc7619-1f13-4bd3-930f-5bd80dd45556");
                _submitaddproductkeyInfo = new RepoItemInfo(this, "SubmitAddProductKey", ".//button[#'submitAddProductKey']", 30000, null, "8c7aab88-8568-42a7-9c03-32bb70563549");
                _select2resultlabel5Info = new RepoItemInfo(this, "Select2ResultLabel5", ".//div[#'select2-result-label-5']", 30000, null, "811d710c-e5e2-4300-8e95-c58007eff3b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b282e6c-ae7f-4b08-bb24-4e6b3249eb04")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b282e6c-ae7f-4b08-bb24-4e6b3249eb04")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagRefresh item.
            /// </summary>
            [RepositoryItem("56e65335-aba5-40f2-9444-10af6046c690")]
            public virtual Ranorex.SpanTag SpanTagRefresh
            {
                get
                {
                    return _spantagrefreshInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagRefresh item info.
            /// </summary>
            [RepositoryItemInfo("56e65335-aba5-40f2-9444-10af6046c690")]
            public virtual RepoItemInfo SpanTagRefreshInfo
            {
                get
                {
                    return _spantagrefreshInfo;
                }
            }

            /// <summary>
            /// The SpanTagAdd item.
            /// </summary>
            [RepositoryItem("70a944cc-7e51-4463-8a21-3a2f857a2300")]
            public virtual Ranorex.SpanTag SpanTagAdd
            {
                get
                {
                    return _spantagaddInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("70a944cc-7e51-4463-8a21-3a2f857a2300")]
            public virtual RepoItemInfo SpanTagAddInfo
            {
                get
                {
                    return _spantagaddInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("4efa5b3b-7dbc-4cbe-9ea7-30fc13a241c2")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("4efa5b3b-7dbc-4cbe-9ea7-30fc13a241c2")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The SomeBTag item.
            /// </summary>
            [RepositoryItem("cdea1b4c-a733-424f-a718-736092f4bb5a")]
            public virtual Ranorex.BTag SomeBTag
            {
                get
                {
                    return _somebtagInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag item info.
            /// </summary>
            [RepositoryItemInfo("cdea1b4c-a733-424f-a718-736092f4bb5a")]
            public virtual RepoItemInfo SomeBTagInfo
            {
                get
                {
                    return _somebtagInfo;
                }
            }

            /// <summary>
            /// The Select2ResultLabel3 item.
            /// </summary>
            [RepositoryItem("218a2c4d-6bc7-4ec4-a7da-038ef3d75d98")]
            public virtual Ranorex.DivTag Select2ResultLabel3
            {
                get
                {
                    return _select2resultlabel3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Select2ResultLabel3 item info.
            /// </summary>
            [RepositoryItemInfo("218a2c4d-6bc7-4ec4-a7da-038ef3d75d98")]
            public virtual RepoItemInfo Select2ResultLabel3Info
            {
                get
                {
                    return _select2resultlabel3Info;
                }
            }

            /// <summary>
            /// The SomeBTag1 item.
            /// </summary>
            [RepositoryItem("2e9335c0-9a7b-49af-8521-133aaf19ae08")]
            public virtual Ranorex.BTag SomeBTag1
            {
                get
                {
                    return _somebtag1Info.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The SomeBTag1 item info.
            /// </summary>
            [RepositoryItemInfo("2e9335c0-9a7b-49af-8521-133aaf19ae08")]
            public virtual RepoItemInfo SomeBTag1Info
            {
                get
                {
                    return _somebtag1Info;
                }
            }

            /// <summary>
            /// The Select2ResultLabel4 item.
            /// </summary>
            [RepositoryItem("1ed1677a-10e8-4657-826e-ce409bbc7509")]
            public virtual Ranorex.DivTag Select2ResultLabel4
            {
                get
                {
                    return _select2resultlabel4Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Select2ResultLabel4 item info.
            /// </summary>
            [RepositoryItemInfo("1ed1677a-10e8-4657-826e-ce409bbc7509")]
            public virtual RepoItemInfo Select2ResultLabel4Info
            {
                get
                {
                    return _select2resultlabel4Info;
                }
            }

            /// <summary>
            /// The SelectLanguagesSubmit item.
            /// </summary>
            [RepositoryItem("ad00f709-79a7-43e5-a56e-3c1f9d92583a")]
            public virtual Ranorex.ButtonTag SelectLanguagesSubmit
            {
                get
                {
                    return _selectlanguagessubmitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SelectLanguagesSubmit item info.
            /// </summary>
            [RepositoryItemInfo("ad00f709-79a7-43e5-a56e-3c1f9d92583a")]
            public virtual RepoItemInfo SelectLanguagesSubmitInfo
            {
                get
                {
                    return _selectlanguagessubmitInfo;
                }
            }

            /// <summary>
            /// The InputNewProfileName item.
            /// </summary>
            [RepositoryItem("41996b51-bb06-4d9a-9108-96b158a89dc5")]
            public virtual Ranorex.InputTag InputNewProfileName
            {
                get
                {
                    return _inputnewprofilenameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputNewProfileName item info.
            /// </summary>
            [RepositoryItemInfo("41996b51-bb06-4d9a-9108-96b158a89dc5")]
            public virtual RepoItemInfo InputNewProfileNameInfo
            {
                get
                {
                    return _inputnewprofilenameInfo;
                }
            }

            /// <summary>
            /// The InputProfileId item.
            /// </summary>
            [RepositoryItem("a5233ce4-09c0-4c20-9f83-d95406e431f1")]
            public virtual Ranorex.InputTag InputProfileId
            {
                get
                {
                    return _inputprofileidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputProfileId item info.
            /// </summary>
            [RepositoryItemInfo("a5233ce4-09c0-4c20-9f83-d95406e431f1")]
            public virtual RepoItemInfo InputProfileIdInfo
            {
                get
                {
                    return _inputprofileidInfo;
                }
            }

            /// <summary>
            /// The Checkbox item.
            /// </summary>
            [RepositoryItem("86865eb5-39bc-48ce-b242-c496704f23c9")]
            public virtual Ranorex.InputTag Checkbox
            {
                get
                {
                    return _checkboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Checkbox item info.
            /// </summary>
            [RepositoryItemInfo("86865eb5-39bc-48ce-b242-c496704f23c9")]
            public virtual RepoItemInfo CheckboxInfo
            {
                get
                {
                    return _checkboxInfo;
                }
            }

            /// <summary>
            /// The SubmitAddProfile item.
            /// </summary>
            [RepositoryItem("5809620f-756c-428e-a8a7-e94d1602b2cd")]
            public virtual Ranorex.ButtonTag SubmitAddProfile
            {
                get
                {
                    return _submitaddprofileInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAddProfile item info.
            /// </summary>
            [RepositoryItemInfo("5809620f-756c-428e-a8a7-e94d1602b2cd")]
            public virtual RepoItemInfo SubmitAddProfileInfo
            {
                get
                {
                    return _submitaddprofileInfo;
                }
            }

            /// <summary>
            /// The ProfileWithTm item.
            /// </summary>
            [RepositoryItem("f367118d-53f5-4d6c-9bb6-e9ef0c505170")]
            public virtual Ranorex.TdTag ProfileWithTm
            {
                get
                {
                    return _profilewithtmInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ProfileWithTm item info.
            /// </summary>
            [RepositoryItemInfo("f367118d-53f5-4d6c-9bb6-e9ef0c505170")]
            public virtual RepoItemInfo ProfileWithTmInfo
            {
                get
                {
                    return _profilewithtmInfo;
                }
            }

            /// <summary>
            /// The ATagDelete item.
            /// </summary>
            [RepositoryItem("ecf75698-1543-4786-9cd0-30cd8c458142")]
            public virtual Ranorex.ATag ATagDelete
            {
                get
                {
                    return _atagdeleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagDelete item info.
            /// </summary>
            [RepositoryItemInfo("ecf75698-1543-4786-9cd0-30cd8c458142")]
            public virtual RepoItemInfo ATagDeleteInfo
            {
                get
                {
                    return _atagdeleteInfo;
                }
            }

            /// <summary>
            /// The ButtonTagOK item.
            /// </summary>
            [RepositoryItem("c97e462e-5c98-4605-ae45-207a424b31c0")]
            public virtual Ranorex.ButtonTag ButtonTagOK
            {
                get
                {
                    return _buttontagokInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagOK item info.
            /// </summary>
            [RepositoryItemInfo("c97e462e-5c98-4605-ae45-207a424b31c0")]
            public virtual RepoItemInfo ButtonTagOKInfo
            {
                get
                {
                    return _buttontagokInfo;
                }
            }

            /// <summary>
            /// The AddProfile item.
            /// </summary>
            [RepositoryItem("634149ab-f447-4fb7-b4ff-444b918e5c6b")]
            public virtual Ranorex.ButtonTag AddProfile
            {
                get
                {
                    return _addprofileInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddProfile item info.
            /// </summary>
            [RepositoryItemInfo("634149ab-f447-4fb7-b4ff-444b918e5c6b")]
            public virtual RepoItemInfo AddProfileInfo
            {
                get
                {
                    return _addprofileInfo;
                }
            }

            /// <summary>
            /// The Checkbox1 item.
            /// </summary>
            [RepositoryItem("23fc9158-02ac-4b19-ad36-6f8ccdde1ab9")]
            public virtual Ranorex.InputTag Checkbox1
            {
                get
                {
                    return _checkbox1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Checkbox1 item info.
            /// </summary>
            [RepositoryItemInfo("23fc9158-02ac-4b19-ad36-6f8ccdde1ab9")]
            public virtual RepoItemInfo Checkbox1Info
            {
                get
                {
                    return _checkbox1Info;
                }
            }

            /// <summary>
            /// The ProfileWithUserDict item.
            /// </summary>
            [RepositoryItem("565c3b9e-a20b-496b-ada8-eb54fe739b50")]
            public virtual Ranorex.TdTag ProfileWithUserDict
            {
                get
                {
                    return _profilewithuserdictInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ProfileWithUserDict item info.
            /// </summary>
            [RepositoryItemInfo("565c3b9e-a20b-496b-ada8-eb54fe739b50")]
            public virtual RepoItemInfo ProfileWithUserDictInfo
            {
                get
                {
                    return _profilewithuserdictInfo;
                }
            }

            /// <summary>
            /// The ProfileWithUserDictAndTM item.
            /// </summary>
            [RepositoryItem("0d32c490-0f99-459a-b461-27254b5aa2c3")]
            public virtual Ranorex.TdTag ProfileWithUserDictAndTM
            {
                get
                {
                    return _profilewithuserdictandtmInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ProfileWithUserDictAndTM item info.
            /// </summary>
            [RepositoryItemInfo("0d32c490-0f99-459a-b461-27254b5aa2c3")]
            public virtual RepoItemInfo ProfileWithUserDictAndTMInfo
            {
                get
                {
                    return _profilewithuserdictandtmInfo;
                }
            }

            /// <summary>
            /// The ProfileIdHelp item.
            /// </summary>
            [RepositoryItem("ec54bb7e-4a5e-4b71-a24e-55271ac27c9c")]
            public virtual Ranorex.SpanTag ProfileIdHelp
            {
                get
                {
                    return _profileidhelpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProfileIdHelp item info.
            /// </summary>
            [RepositoryItemInfo("ec54bb7e-4a5e-4b71-a24e-55271ac27c9c")]
            public virtual RepoItemInfo ProfileIdHelpInfo
            {
                get
                {
                    return _profileidhelpInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("8d609d08-bebb-475f-974d-76a56e704c02")]
            public virtual Ranorex.ButtonTag Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("8d609d08-bebb-475f-974d-76a56e704c02")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The LinguisticResources item.
            /// </summary>
            [RepositoryItem("dec782c7-0576-4ab4-ad39-38cf6846ff16")]
            public virtual Ranorex.ATag LinguisticResources
            {
                get
                {
                    return _linguisticresourcesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinguisticResources item info.
            /// </summary>
            [RepositoryItemInfo("dec782c7-0576-4ab4-ad39-38cf6846ff16")]
            public virtual RepoItemInfo LinguisticResourcesInfo
            {
                get
                {
                    return _linguisticresourcesInfo;
                }
            }

            /// <summary>
            /// The Dictionaries item.
            /// </summary>
            [RepositoryItem("c6282c9e-140e-4b75-a2d3-e17acfbf7554")]
            public virtual Ranorex.ATag Dictionaries
            {
                get
                {
                    return _dictionariesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Dictionaries item info.
            /// </summary>
            [RepositoryItemInfo("c6282c9e-140e-4b75-a2d3-e17acfbf7554")]
            public virtual RepoItemInfo DictionariesInfo
            {
                get
                {
                    return _dictionariesInfo;
                }
            }

            /// <summary>
            /// The Dictionaries1 item.
            /// </summary>
            [RepositoryItem("06d122e6-e267-4ee8-bea9-05dd6d41fd11")]
            public virtual Ranorex.H3Tag Dictionaries1
            {
                get
                {
                    return _dictionaries1Info.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Dictionaries1 item info.
            /// </summary>
            [RepositoryItemInfo("06d122e6-e267-4ee8-bea9-05dd6d41fd11")]
            public virtual RepoItemInfo Dictionaries1Info
            {
                get
                {
                    return _dictionaries1Info;
                }
            }

            /// <summary>
            /// The Normalizations item.
            /// </summary>
            [RepositoryItem("e34a084a-e4e1-48fd-9070-f6f308a416ad")]
            public virtual Ranorex.ATag Normalizations
            {
                get
                {
                    return _normalizationsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Normalizations item info.
            /// </summary>
            [RepositoryItemInfo("e34a084a-e4e1-48fd-9070-f6f308a416ad")]
            public virtual RepoItemInfo NormalizationsInfo
            {
                get
                {
                    return _normalizationsInfo;
                }
            }

            /// <summary>
            /// The Normalizations1 item.
            /// </summary>
            [RepositoryItem("98eefab4-cf31-4937-b4b1-056701031fd7")]
            public virtual Ranorex.H3Tag Normalizations1
            {
                get
                {
                    return _normalizations1Info.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Normalizations1 item info.
            /// </summary>
            [RepositoryItemInfo("98eefab4-cf31-4937-b4b1-056701031fd7")]
            public virtual RepoItemInfo Normalizations1Info
            {
                get
                {
                    return _normalizations1Info;
                }
            }

            /// <summary>
            /// The Licenses item.
            /// </summary>
            [RepositoryItem("952c2cf0-6c56-4ff3-b545-a9755697937a")]
            public virtual Ranorex.ATag Licenses
            {
                get
                {
                    return _licensesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Licenses item info.
            /// </summary>
            [RepositoryItemInfo("952c2cf0-6c56-4ff3-b545-a9755697937a")]
            public virtual RepoItemInfo LicensesInfo
            {
                get
                {
                    return _licensesInfo;
                }
            }

            /// <summary>
            /// The Licenses1 item.
            /// </summary>
            [RepositoryItem("4bd45166-72f7-41ab-9420-b2e9293880c4")]
            public virtual Ranorex.H3Tag Licenses1
            {
                get
                {
                    return _licenses1Info.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Licenses1 item info.
            /// </summary>
            [RepositoryItemInfo("4bd45166-72f7-41ab-9420-b2e9293880c4")]
            public virtual RepoItemInfo Licenses1Info
            {
                get
                {
                    return _licenses1Info;
                }
            }

            /// <summary>
            /// The AddProductKeyButton item.
            /// </summary>
            [RepositoryItem("e27fb162-ddff-4423-8519-11002a82271c")]
            public virtual Ranorex.ButtonTag AddProductKeyButton
            {
                get
                {
                    return _addproductkeybuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddProductKeyButton item info.
            /// </summary>
            [RepositoryItemInfo("e27fb162-ddff-4423-8519-11002a82271c")]
            public virtual RepoItemInfo AddProductKeyButtonInfo
            {
                get
                {
                    return _addproductkeybuttonInfo;
                }
            }

            /// <summary>
            /// The AddAProductKey item.
            /// </summary>
            [RepositoryItem("21951eee-db38-4a88-8670-619a0eb87915")]
            public virtual Ranorex.H3Tag AddAProductKey
            {
                get
                {
                    return _addaproductkeyInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The AddAProductKey item info.
            /// </summary>
            [RepositoryItemInfo("21951eee-db38-4a88-8670-619a0eb87915")]
            public virtual RepoItemInfo AddAProductKeyInfo
            {
                get
                {
                    return _addaproductkeyInfo;
                }
            }

            /// <summary>
            /// The Close1 item.
            /// </summary>
            [RepositoryItem("cffc7619-1f13-4bd3-930f-5bd80dd45556")]
            public virtual Ranorex.ButtonTag Close1
            {
                get
                {
                    return _close1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Close1 item info.
            /// </summary>
            [RepositoryItemInfo("cffc7619-1f13-4bd3-930f-5bd80dd45556")]
            public virtual RepoItemInfo Close1Info
            {
                get
                {
                    return _close1Info;
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item.
            /// </summary>
            [RepositoryItem("8c7aab88-8568-42a7-9c03-32bb70563549")]
            public virtual Ranorex.ButtonTag SubmitAddProductKey
            {
                get
                {
                    return _submitaddproductkeyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item info.
            /// </summary>
            [RepositoryItemInfo("8c7aab88-8568-42a7-9c03-32bb70563549")]
            public virtual RepoItemInfo SubmitAddProductKeyInfo
            {
                get
                {
                    return _submitaddproductkeyInfo;
                }
            }

            /// <summary>
            /// The Select2ResultLabel5 item.
            /// </summary>
            [RepositoryItem("811d710c-e5e2-4300-8e95-c58007eff3b2")]
            public virtual Ranorex.DivTag Select2ResultLabel5
            {
                get
                {
                    return _select2resultlabel5Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Select2ResultLabel5 item info.
            /// </summary>
            [RepositoryItemInfo("811d710c-e5e2-4300-8e95-c58007eff3b2")]
            public virtual RepoItemInfo Select2ResultLabel5Info
            {
                get
                {
                    return _select2resultlabel5Info;
                }
            }
        }

        /// <summary>
        /// The TranslationResourcesAppFolder folder.
        /// </summary>
        [RepositoryFolder("25b51433-0345-4a65-b956-e8d92dfa5fd3")]
        public partial class TranslationResourcesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _linkInfo;

            /// <summary>
            /// Creates a new TranslationResources  folder.
            /// </summary>
            public TranslationResourcesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TranslationResources", "/form[@title='Translation Resources']", parentFolder, 30000, null, true, "25b51433-0345-4a65-b956-e8d92dfa5fd3", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "8af509f2-0fdb-4785-95c0-041b32ca4eee");
                _linkInfo = new RepoItemInfo(this, "Link", "?/?/container[@accessiblename='Translation Resources']/?/?/link[@url='https://trs.systran.net/']", 30000, null, "0baf1af5-9d77-45c8-9f04-8013d981b29a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("25b51433-0345-4a65-b956-e8d92dfa5fd3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("25b51433-0345-4a65-b956-e8d92dfa5fd3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("8af509f2-0fdb-4785-95c0-041b32ca4eee")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("8af509f2-0fdb-4785-95c0-041b32ca4eee")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Link item.
            /// </summary>
            [RepositoryItem("0baf1af5-9d77-45c8-9f04-8013d981b29a")]
            public virtual Ranorex.Link Link
            {
                get
                {
                    return _linkInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Link item info.
            /// </summary>
            [RepositoryItemInfo("0baf1af5-9d77-45c8-9f04-8013d981b29a")]
            public virtual RepoItemInfo LinkInfo
            {
                get
                {
                    return _linkInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("096128c6-696a-4ade-9851-1e797c26b364")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systranquickfiletranslatorInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "096128c6-696a-4ade-9851-1e797c26b364", "")
            {
                _systranquickfiletranslatorInfo = new RepoItemInfo(this, "SYSTRANQuickFileTranslator", "form[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^SYSTRAN\\ Quick\\ File\\ Transl']", 30000, null, "f44ace83-5153-4f3d-aed7-8d7f92bb5014");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("096128c6-696a-4ade-9851-1e797c26b364")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("096128c6-696a-4ade-9851-1e797c26b364")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SYSTRANQuickFileTranslator item.
            /// </summary>
            [RepositoryItem("f44ace83-5153-4f3d-aed7-8d7f92bb5014")]
            public virtual Ranorex.Button SYSTRANQuickFileTranslator
            {
                get
                {
                    return _systranquickfiletranslatorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SYSTRANQuickFileTranslator item info.
            /// </summary>
            [RepositoryItemInfo("f44ace83-5153-4f3d-aed7-8d7f92bb5014")]
            public virtual RepoItemInfo SYSTRANQuickFileTranslatorInfo
            {
                get
                {
                    return _systranquickfiletranslatorInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRANQuickFileTranslatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("e9c42457-a977-4a67-988a-783a8b97d7d3")]
        public partial class SYSTRANQuickFileTranslatorAppFolder : RepoGenBaseFolder
        {
            LanguageManagerRepositoryFolders.SomeContainerFolder _somecontainer;

            /// <summary>
            /// Creates a new SYSTRANQuickFileTranslator  folder.
            /// </summary>
            public SYSTRANQuickFileTranslatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANQuickFileTranslator", "/form[@wpfnative='True' and @title~'^SYSTRAN\\ Quick\\ File\\ Transl' and @processname='SYSTRAN.QuickFileTranslator']", parentFolder, 30000, null, true, "e9c42457-a977-4a67-988a-783a8b97d7d3", "")
            {
                _somecontainer = new LanguageManagerRepositoryFolders.SomeContainerFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9c42457-a977-4a67-988a-783a8b97d7d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9c42457-a977-4a67-988a-783a8b97d7d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeContainer folder.
            /// </summary>
            [RepositoryFolder("b41508eb-62a8-4225-876f-f265f8a793ce")]
            public virtual LanguageManagerRepositoryFolders.SomeContainerFolder SomeContainer
            {
                get { return _somecontainer; }
            }
        }

        /// <summary>
        /// The SomeContainerFolder folder.
        /// </summary>
        [RepositoryFolder("b41508eb-62a8-4225-876f-f265f8a793ce")]
        public partial class SomeContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _backgroundInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _canceltranslationInfo;

            /// <summary>
            /// Creates a new SomeContainer  folder.
            /// </summary>
            public SomeContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer", "container/element[1]/container/element[7]/container[@automationid='root']//element[@automationid='transitioning']//element[@automationid='CurrentContentPresentationSite']/container", parentFolder, 30000, null, false, "b41508eb-62a8-4225-876f-f265f8a793ce", "")
            {
                _backgroundInfo = new RepoItemInfo(this, "Background", "?/?/element/container/element/container/container/button[@text='Translate']/?/?/element[@automationid='Background']", 30000, null, "208f43c0-e015-4077-ab94-521d42fb6c06");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element/element/container/container/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/container/container[2]/container/element[3]/container/container[1]/text[@automationid='mSourceRootFolderTextBox']/?/?/container[@automationid='PART_InnerGrid']/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "768ba444-069d-44f8-8c48-f4b5f8447c3d");
                _canceltranslationInfo = new RepoItemInfo(this, "CancelTranslation", "element/element/container/element/?/?/button[@text='Cancel translation']/?/?/element[@automationid='contentPresenter']/text[@caption='Cancel translation']", 30000, null, "d7bac550-169a-4dfc-a49c-c9b12af9c55b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b41508eb-62a8-4225-876f-f265f8a793ce")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b41508eb-62a8-4225-876f-f265f8a793ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Background item.
            /// </summary>
            [RepositoryItem("208f43c0-e015-4077-ab94-521d42fb6c06")]
            public virtual Ranorex.Unknown Background
            {
                get
                {
                    return _backgroundInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Background item info.
            /// </summary>
            [RepositoryItemInfo("208f43c0-e015-4077-ab94-521d42fb6c06")]
            public virtual RepoItemInfo BackgroundInfo
            {
                get
                {
                    return _backgroundInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("768ba444-069d-44f8-8c48-f4b5f8447c3d")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("768ba444-069d-44f8-8c48-f4b5f8447c3d")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The CancelTranslation item.
            /// </summary>
            [RepositoryItem("d7bac550-169a-4dfc-a49c-c9b12af9c55b")]
            public virtual Ranorex.Text CancelTranslation
            {
                get
                {
                    return _canceltranslationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CancelTranslation item info.
            /// </summary>
            [RepositoryItemInfo("d7bac550-169a-4dfc-a49c-c9b12af9c55b")]
            public virtual RepoItemInfo CancelTranslationInfo
            {
                get
                {
                    return _canceltranslationInfo;
                }
            }
        }

        /// <summary>
        /// The AbortTranslationAppFolder folder.
        /// </summary>
        [RepositoryFolder("7a26042b-2fcd-4ff8-a3f4-09932e50163e")]
        public partial class AbortTranslationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new AbortTranslation  folder.
            /// </summary>
            public AbortTranslationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AbortTranslation", "/form[@title='Abort translation']", parentFolder, 30000, null, true, "7a26042b-2fcd-4ff8-a3f4-09932e50163e", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "1d816c15-94c2-40c9-819d-25575ab0c64c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7a26042b-2fcd-4ff8-a3f4-09932e50163e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a26042b-2fcd-4ff8-a3f4-09932e50163e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("1d816c15-94c2-40c9-819d-25575ab0c64c")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("1d816c15-94c2-40c9-819d-25575ab0c64c")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}