///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LanguageManager
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Linguistic_Resources_Normalization_Check recording.
    /// </summary>
    [TestModule("231efb7b-7776-4064-853d-a4af2a7c2650", ModuleType.Recording, 1)]
    public partial class Linguistic_Resources_Normalization_Check : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LanguageManagerRepository repository.
        /// </summary>
        public static LanguageManagerRepository repo = LanguageManagerRepository.Instance;

        static Linguistic_Resources_Normalization_Check instance = new Linguistic_Resources_Normalization_Check();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Linguistic_Resources_Normalization_Check()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Linguistic_Resources_Normalization_Check Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANLanguageManager1.LinguisticResources' at 136;25.", repo.SYSTRANLanguageManager1.LinguisticResourcesInfo, new RecordItemIndex(0));
            repo.SYSTRANLanguageManager1.LinguisticResources.Click("136;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SYSTRANLanguageManager1.Normalizations' at 90;11.", repo.SYSTRANLanguageManager1.NormalizationsInfo, new RecordItemIndex(1));
            repo.SYSTRANLanguageManager1.Normalizations.Click("90;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Normalizations') on item 'SYSTRANLanguageManager1.Normalizations1'.", repo.SYSTRANLanguageManager1.Normalizations1Info, new RecordItemIndex(2));
            Validate.Attribute(repo.SYSTRANLanguageManager1.Normalizations1Info, "InnerText", "Normalizations");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
