///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace testSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("fe6553c7-2340-4204-a433-526a6ff2dd03")]
    public partial class testSolutionRepository : RepoGenBaseFolder
    {
        static testSolutionRepository instance = new testSolutionRepository();
        testSolutionRepositoryFolders.InternetExplorerAppFolder _internetexplorer;
        testSolutionRepositoryFolders.SYSTRANLanguageManagerAppFolder _systranlanguagemanager;

        /// <summary>
        /// Gets the singleton class instance representing the testSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("fe6553c7-2340-4204-a433-526a6ff2dd03")]
        public static testSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testSolutionRepository() 
            : base("testSolutionRepository", "/", null, 0, false, "fe6553c7-2340-4204-a433-526a6ff2dd03", ".\\RepositoryImages\\testSolutionRepositoryfe6553c7.rximgres")
        {
            _internetexplorer = new testSolutionRepositoryFolders.InternetExplorerAppFolder(this);
            _systranlanguagemanager = new testSolutionRepositoryFolders.SYSTRANLanguageManagerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fe6553c7-2340-4204-a433-526a6ff2dd03")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The InternetExplorer folder.
        /// </summary>
        [RepositoryFolder("f823082a-a7b2-4ef2-a1c0-d9f0ce5fcc6e")]
        public virtual testSolutionRepositoryFolders.InternetExplorerAppFolder InternetExplorer
        {
            get { return _internetexplorer; }
        }

        /// <summary>
        /// The SYSTRANLanguageManager folder.
        /// </summary>
        [RepositoryFolder("902c6c2c-c230-466a-a889-322c5ec1bdc0")]
        public virtual testSolutionRepositoryFolders.SYSTRANLanguageManagerAppFolder SYSTRANLanguageManager
        {
            get { return _systranlanguagemanager; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class testSolutionRepositoryFolders
    {
        /// <summary>
        /// The InternetExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f823082a-a7b2-4ef2-a1c0-d9f0ce5fcc6e")]
        public partial class InternetExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _webaddressfieldInfo;

            /// <summary>
            /// Creates a new InternetExplorer  folder.
            /// </summary>
            public InternetExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InternetExplorer", "/form", parentFolder, 30000, null, true, "f823082a-a7b2-4ef2-a1c0-d9f0ce5fcc6e", "")
            {
                _webaddressfieldInfo = new RepoItemInfo(this, "WebAddressField", "?/?/form/element[2]/element/text[@accessiblename='Address']", 30000, null, "a1ba47fc-6da2-41ed-9ca3-2c08b56e056c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f823082a-a7b2-4ef2-a1c0-d9f0ce5fcc6e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f823082a-a7b2-4ef2-a1c0-d9f0ce5fcc6e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebAddressField item.
            /// </summary>
            [RepositoryItem("a1ba47fc-6da2-41ed-9ca3-2c08b56e056c")]
            public virtual Ranorex.Text WebAddressField
            {
                get
                {
                    return _webaddressfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The WebAddressField item info.
            /// </summary>
            [RepositoryItemInfo("a1ba47fc-6da2-41ed-9ca3-2c08b56e056c")]
            public virtual RepoItemInfo WebAddressFieldInfo
            {
                get
                {
                    return _webaddressfieldInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRANLanguageManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("902c6c2c-c230-466a-a889-322c5ec1bdc0")]
        public partial class SYSTRANLanguageManagerAppFolder : RepoGenBaseFolder
        {
            testSolutionRepositoryFolders.LicenseListContentFolder _licenselistcontent;
            RepoItemInfo _licensesInfo;
            RepoItemInfo _addproductkeybuttonInfo;
            RepoItemInfo _inputproductkeyInfo;
            RepoItemInfo _submitaddproductkeyInfo;
            RepoItemInfo _buttontagokInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new SYSTRANLanguageManager  folder.
            /// </summary>
            public SYSTRANLanguageManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANLanguageManager", "/dom[@domain='localhost:3500']", parentFolder, 30000, null, false, "902c6c2c-c230-466a-a889-322c5ec1bdc0", "")
            {
                _licenselistcontent = new testSolutionRepositoryFolders.LicenseListContentFolder(this);
                _licensesInfo = new RepoItemInfo(this, "Licenses", ".//span[#'errorMessage']/a[@innertext='Licenses']", 30000, null, "d1854dba-1f7c-49a4-b401-d1db496d93b3");
                _addproductkeybuttonInfo = new RepoItemInfo(this, "AddProductKeyButton", ".//button[#'addProductKeyButton']", 30000, null, "1d2f703a-22f6-4953-8f33-aa0739c55fdb");
                _inputproductkeyInfo = new RepoItemInfo(this, "InputProductKey", ".//textarea[#'inputProductKey']", 30000, null, "52e8b69d-fe7c-46a3-ad63-ca1c8b58df99");
                _submitaddproductkeyInfo = new RepoItemInfo(this, "SubmitAddProductKey", ".//button[#'submitAddProductKey']", 30000, null, "c78a9004-a500-485b-8be6-0ec7891d900b");
                _buttontagokInfo = new RepoItemInfo(this, "ButtonTagOK", "body/div[6]/div/div/div[2]/button[@innertext='OK']", 30000, null, "37f5f0fb-c882-4b33-8ccc-fe09ff1d7599");
                _closeInfo = new RepoItemInfo(this, "Close", ".//div[#'addProductKeyModal']/div/div/div[3]/button[@innertext='Close']", 30000, null, "e75d5e89-c13f-4b46-b48d-45dd124f0f73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("902c6c2c-c230-466a-a889-322c5ec1bdc0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("902c6c2c-c230-466a-a889-322c5ec1bdc0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Licenses item.
            /// </summary>
            [RepositoryItem("d1854dba-1f7c-49a4-b401-d1db496d93b3")]
            public virtual Ranorex.ATag Licenses
            {
                get
                {
                    return _licensesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Licenses item info.
            /// </summary>
            [RepositoryItemInfo("d1854dba-1f7c-49a4-b401-d1db496d93b3")]
            public virtual RepoItemInfo LicensesInfo
            {
                get
                {
                    return _licensesInfo;
                }
            }

            /// <summary>
            /// The AddProductKeyButton item.
            /// </summary>
            [RepositoryItem("1d2f703a-22f6-4953-8f33-aa0739c55fdb")]
            public virtual Ranorex.ButtonTag AddProductKeyButton
            {
                get
                {
                    return _addproductkeybuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddProductKeyButton item info.
            /// </summary>
            [RepositoryItemInfo("1d2f703a-22f6-4953-8f33-aa0739c55fdb")]
            public virtual RepoItemInfo AddProductKeyButtonInfo
            {
                get
                {
                    return _addproductkeybuttonInfo;
                }
            }

            /// <summary>
            /// The InputProductKey item.
            /// </summary>
            [RepositoryItem("52e8b69d-fe7c-46a3-ad63-ca1c8b58df99")]
            public virtual Ranorex.TextAreaTag InputProductKey
            {
                get
                {
                    return _inputproductkeyInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The InputProductKey item info.
            /// </summary>
            [RepositoryItemInfo("52e8b69d-fe7c-46a3-ad63-ca1c8b58df99")]
            public virtual RepoItemInfo InputProductKeyInfo
            {
                get
                {
                    return _inputproductkeyInfo;
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item.
            /// </summary>
            [RepositoryItem("c78a9004-a500-485b-8be6-0ec7891d900b")]
            public virtual Ranorex.ButtonTag SubmitAddProductKey
            {
                get
                {
                    return _submitaddproductkeyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item info.
            /// </summary>
            [RepositoryItemInfo("c78a9004-a500-485b-8be6-0ec7891d900b")]
            public virtual RepoItemInfo SubmitAddProductKeyInfo
            {
                get
                {
                    return _submitaddproductkeyInfo;
                }
            }

            /// <summary>
            /// The ButtonTagOK item.
            /// </summary>
            [RepositoryItem("37f5f0fb-c882-4b33-8ccc-fe09ff1d7599")]
            public virtual Ranorex.ButtonTag ButtonTagOK
            {
                get
                {
                    return _buttontagokInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagOK item info.
            /// </summary>
            [RepositoryItemInfo("37f5f0fb-c882-4b33-8ccc-fe09ff1d7599")]
            public virtual RepoItemInfo ButtonTagOKInfo
            {
                get
                {
                    return _buttontagokInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("e75d5e89-c13f-4b46-b48d-45dd124f0f73")]
            public virtual Ranorex.ButtonTag Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("e75d5e89-c13f-4b46-b48d-45dd124f0f73")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The LicenseListContent folder.
            /// </summary>
            [RepositoryFolder("99df48c8-dd7c-4756-bfa5-e71eaf397117")]
            public virtual testSolutionRepositoryFolders.LicenseListContentFolder LicenseListContent
            {
                get { return _licenselistcontent; }
            }
        }

        /// <summary>
        /// The LicenseListContentFolder folder.
        /// </summary>
        [RepositoryFolder("99df48c8-dd7c-4756-bfa5-e71eaf397117")]
        public partial class LicenseListContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _delete1Info;
            RepoItemInfo _onlineactivationInfo;
            RepoItemInfo _deleteInfo;

            /// <summary>
            /// Creates a new LicenseListContent  folder.
            /// </summary>
            public LicenseListContentFolder(RepoGenBaseFolder parentFolder) :
                    base("LicenseListContent", ".//div[#'licenseListContent']", parentFolder, 30000, null, false, "99df48c8-dd7c-4756-bfa5-e71eaf397117", "")
            {
                _delete1Info = new RepoItemInfo(this, "Delete1", "div/div[4]//a[@innertext='Delete']", 30000, null, "64551bef-90f2-4302-bcd5-34208bacb7c6");
                _onlineactivationInfo = new RepoItemInfo(this, "OnlineActivation", "div[1]/div[12]/?/?/button[@innertext='Online Activation']", 30000, null, "361067bf-6577-4272-a7f0-3ecccfb7972e");
                _deleteInfo = new RepoItemInfo(this, "Delete", "div[1]/div[13]//a[@innertext='Delete']", 30000, null, "2a7f51c7-9584-48f8-b42f-4076e5e87ec1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("99df48c8-dd7c-4756-bfa5-e71eaf397117")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("99df48c8-dd7c-4756-bfa5-e71eaf397117")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Delete1 item.
            /// </summary>
            [RepositoryItem("64551bef-90f2-4302-bcd5-34208bacb7c6")]
            public virtual Ranorex.ATag Delete1
            {
                get
                {
                    return _delete1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete1 item info.
            /// </summary>
            [RepositoryItemInfo("64551bef-90f2-4302-bcd5-34208bacb7c6")]
            public virtual RepoItemInfo Delete1Info
            {
                get
                {
                    return _delete1Info;
                }
            }

            /// <summary>
            /// The OnlineActivation item.
            /// </summary>
            [RepositoryItem("361067bf-6577-4272-a7f0-3ecccfb7972e")]
            public virtual Ranorex.ButtonTag OnlineActivation
            {
                get
                {
                    return _onlineactivationInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OnlineActivation item info.
            /// </summary>
            [RepositoryItemInfo("361067bf-6577-4272-a7f0-3ecccfb7972e")]
            public virtual RepoItemInfo OnlineActivationInfo
            {
                get
                {
                    return _onlineactivationInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("2a7f51c7-9584-48f8-b42f-4076e5e87ec1")]
            public virtual Ranorex.ATag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("2a7f51c7-9584-48f8-b42f-4076e5e87ec1")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}