///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace testAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("370aef2b-a6a1-4915-bd69-493132b16183")]
    public partial class testAutomationRepository : RepoGenBaseFolder
    {
        static testAutomationRepository instance = new testAutomationRepository();
        testAutomationRepositoryFolders.SignInAppFolder _signin;
        testAutomationRepositoryFolders.SYSTRANAccountsSignInAppFolder _systranaccountssignin;
        testAutomationRepositoryFolders.TranslationResourcesAppFolder _translationresources;
        testAutomationRepositoryFolders.PackagesAppFolder _packages;
        testAutomationRepositoryFolders.EnterNameOfFileToSaveToAppFolder _enternameoffiletosaveto;
        testAutomationRepositoryFolders.SYSTRAN8TRANSLATORAppFolder _systran8translator;
        testAutomationRepositoryFolders.SYSTRAN8TRANSLATORUninstallAppFolder _systran8translatoruninstall;
        testAutomationRepositoryFolders.OpeningSYSTRAN8TRANSLATORProfessionaAppFolder _openingsystran8translatorprofessiona;
        testAutomationRepositoryFolders.WizardFormAppFolder _wizardform;
        testAutomationRepositoryFolders.DeleteFileAppFolder _deletefile;
        testAutomationRepositoryFolders.SYSTRANLanguageManagerAppFolder _systranlanguagemanager;
        testAutomationRepositoryFolders.ConfirmSaveAsAppFolder _confirmsaveas;
        testAutomationRepositoryFolders.LicensesAppFolder _licenses;

        /// <summary>
        /// Gets the singleton class instance representing the testAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("370aef2b-a6a1-4915-bd69-493132b16183")]
        public static testAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testAutomationRepository() 
            : base("testAutomationRepository", "/", null, 0, false, "370aef2b-a6a1-4915-bd69-493132b16183", ".\\RepositoryImages\\testAutomationRepository370aef2b.rximgres")
        {
            _signin = new testAutomationRepositoryFolders.SignInAppFolder(this);
            _systranaccountssignin = new testAutomationRepositoryFolders.SYSTRANAccountsSignInAppFolder(this);
            _translationresources = new testAutomationRepositoryFolders.TranslationResourcesAppFolder(this);
            _packages = new testAutomationRepositoryFolders.PackagesAppFolder(this);
            _enternameoffiletosaveto = new testAutomationRepositoryFolders.EnterNameOfFileToSaveToAppFolder(this);
            _systran8translator = new testAutomationRepositoryFolders.SYSTRAN8TRANSLATORAppFolder(this);
            _systran8translatoruninstall = new testAutomationRepositoryFolders.SYSTRAN8TRANSLATORUninstallAppFolder(this);
            _openingsystran8translatorprofessiona = new testAutomationRepositoryFolders.OpeningSYSTRAN8TRANSLATORProfessionaAppFolder(this);
            _wizardform = new testAutomationRepositoryFolders.WizardFormAppFolder(this);
            _deletefile = new testAutomationRepositoryFolders.DeleteFileAppFolder(this);
            _systranlanguagemanager = new testAutomationRepositoryFolders.SYSTRANLanguageManagerAppFolder(this);
            _confirmsaveas = new testAutomationRepositoryFolders.ConfirmSaveAsAppFolder(this);
            _licenses = new testAutomationRepositoryFolders.LicensesAppFolder(this);
        }

#region Variables

        string _NewVariable = "570";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("c81ff574-46b9-4820-88b7-54ba72980c91")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("370aef2b-a6a1-4915-bd69-493132b16183")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SignIn folder.
        /// </summary>
        [RepositoryFolder("093aa11c-9314-43bd-85b0-89b5ace21505")]
        public virtual testAutomationRepositoryFolders.SignInAppFolder SignIn
        {
            get { return _signin; }
        }

        /// <summary>
        /// The SYSTRANAccountsSignIn folder.
        /// </summary>
        [RepositoryFolder("75d7e3de-e277-4fe1-9bf5-f6ee77ad6f0b")]
        public virtual testAutomationRepositoryFolders.SYSTRANAccountsSignInAppFolder SYSTRANAccountsSignIn
        {
            get { return _systranaccountssignin; }
        }

        /// <summary>
        /// The TranslationResources folder.
        /// </summary>
        [RepositoryFolder("fc6abb1a-2d49-4d9f-aac6-63a484199323")]
        public virtual testAutomationRepositoryFolders.TranslationResourcesAppFolder TranslationResources
        {
            get { return _translationresources; }
        }

        /// <summary>
        /// The Packages folder.
        /// </summary>
        [RepositoryFolder("ca88c4c2-cdc1-4a90-88e3-32f481f41631")]
        public virtual testAutomationRepositoryFolders.PackagesAppFolder Packages
        {
            get { return _packages; }
        }

        /// <summary>
        /// The EnterNameOfFileToSaveTo folder.
        /// </summary>
        [RepositoryFolder("7fd806c1-0051-4809-8797-022072c63766")]
        public virtual testAutomationRepositoryFolders.EnterNameOfFileToSaveToAppFolder EnterNameOfFileToSaveTo
        {
            get { return _enternameoffiletosaveto; }
        }

        /// <summary>
        /// The SYSTRAN8TRANSLATOR folder.
        /// </summary>
        [RepositoryFolder("47ef1190-c397-4a39-8132-62513cd8b419")]
        public virtual testAutomationRepositoryFolders.SYSTRAN8TRANSLATORAppFolder SYSTRAN8TRANSLATOR
        {
            get { return _systran8translator; }
        }

        /// <summary>
        /// The SYSTRAN8TRANSLATORUninstall folder.
        /// </summary>
        [RepositoryFolder("2042364c-910a-4c6e-9535-803cc7103239")]
        public virtual testAutomationRepositoryFolders.SYSTRAN8TRANSLATORUninstallAppFolder SYSTRAN8TRANSLATORUninstall
        {
            get { return _systran8translatoruninstall; }
        }

        /// <summary>
        /// The OpeningSYSTRAN8TRANSLATORProfessiona folder.
        /// </summary>
        [RepositoryFolder("5731371a-f975-4ecb-875c-b3e7a81baf4d")]
        public virtual testAutomationRepositoryFolders.OpeningSYSTRAN8TRANSLATORProfessionaAppFolder OpeningSYSTRAN8TRANSLATORProfessiona
        {
            get { return _openingsystran8translatorprofessiona; }
        }

        /// <summary>
        /// The WizardForm folder.
        /// </summary>
        [RepositoryFolder("2b91ff72-7c40-4fd7-ab88-e312f6cc8c3e")]
        public virtual testAutomationRepositoryFolders.WizardFormAppFolder WizardForm
        {
            get { return _wizardform; }
        }

        /// <summary>
        /// The DeleteFile folder.
        /// </summary>
        [RepositoryFolder("696e833e-cf5b-41db-9776-40430bbc28aa")]
        public virtual testAutomationRepositoryFolders.DeleteFileAppFolder DeleteFile
        {
            get { return _deletefile; }
        }

        /// <summary>
        /// The SYSTRANLanguageManager folder.
        /// </summary>
        [RepositoryFolder("87651c18-525b-4cf0-b3ce-6d57e1f16fc9")]
        public virtual testAutomationRepositoryFolders.SYSTRANLanguageManagerAppFolder SYSTRANLanguageManager
        {
            get { return _systranlanguagemanager; }
        }

        /// <summary>
        /// The ConfirmSaveAs folder.
        /// </summary>
        [RepositoryFolder("93f24892-b257-4141-85bf-b3a1b8f9cb56")]
        public virtual testAutomationRepositoryFolders.ConfirmSaveAsAppFolder ConfirmSaveAs
        {
            get { return _confirmsaveas; }
        }

        /// <summary>
        /// The Licenses folder.
        /// </summary>
        [RepositoryFolder("a4acb732-f92c-4254-9e4f-6a2ab6bd2781")]
        public virtual testAutomationRepositoryFolders.LicensesAppFolder Licenses
        {
            get { return _licenses; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class testAutomationRepositoryFolders
    {
        /// <summary>
        /// The SignInAppFolder folder.
        /// </summary>
        [RepositoryFolder("093aa11c-9314-43bd-85b0-89b5ace21505")]
        public partial class SignInAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _continuewithInfo;

            /// <summary>
            /// Creates a new SignIn  folder.
            /// </summary>
            public SignInAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignIn", "/dom[@caption='Sign in']", parentFolder, 30000, null, false, "093aa11c-9314-43bd-85b0-89b5ace21505", "")
            {
                _continuewithInfo = new RepoItemInfo(this, "ContinueWith", ".//div[#'main']//a[@innertext='Continue with ']", 30000, null, "68966b3e-4b1e-44f6-94b7-76f357257b84");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("093aa11c-9314-43bd-85b0-89b5ace21505")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("093aa11c-9314-43bd-85b0-89b5ace21505")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContinueWith item.
            /// </summary>
            [RepositoryItem("68966b3e-4b1e-44f6-94b7-76f357257b84")]
            public virtual Ranorex.ATag ContinueWith
            {
                get
                {
                    return _continuewithInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ContinueWith item info.
            /// </summary>
            [RepositoryItemInfo("68966b3e-4b1e-44f6-94b7-76f357257b84")]
            public virtual RepoItemInfo ContinueWithInfo
            {
                get
                {
                    return _continuewithInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRANAccountsSignInAppFolder folder.
        /// </summary>
        [RepositoryFolder("75d7e3de-e277-4fe1-9bf5-f6ee77ad6f0b")]
        public partial class SYSTRANAccountsSignInAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usrnmInfo;
            RepoItemInfo _psswdInfo;
            RepoItemInfo _submitloginInfo;

            /// <summary>
            /// Creates a new SYSTRANAccountsSignIn  folder.
            /// </summary>
            public SYSTRANAccountsSignInAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANAccountsSignIn", "/dom[@domain='login.systran.net']", parentFolder, 30000, null, false, "75d7e3de-e277-4fe1-9bf5-f6ee77ad6f0b", "")
            {
                _usrnmInfo = new RepoItemInfo(this, "Usrnm", ".//input[#'usrnm']", 30000, null, "4b032f82-d437-4341-9d5d-f64776c034c8");
                _psswdInfo = new RepoItemInfo(this, "Psswd", ".//input[#'psswd']", 30000, null, "165130f5-d0d5-4391-95f1-0f016f4c88c5");
                _submitloginInfo = new RepoItemInfo(this, "SubmitLogin", ".//input[#'submit_login']", 30000, null, "919b7359-893c-40bd-a5d1-052cda767882");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75d7e3de-e277-4fe1-9bf5-f6ee77ad6f0b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75d7e3de-e277-4fe1-9bf5-f6ee77ad6f0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Usrnm item.
            /// </summary>
            [RepositoryItem("4b032f82-d437-4341-9d5d-f64776c034c8")]
            public virtual Ranorex.InputTag Usrnm
            {
                get
                {
                    return _usrnmInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Usrnm item info.
            /// </summary>
            [RepositoryItemInfo("4b032f82-d437-4341-9d5d-f64776c034c8")]
            public virtual RepoItemInfo UsrnmInfo
            {
                get
                {
                    return _usrnmInfo;
                }
            }

            /// <summary>
            /// The Psswd item.
            /// </summary>
            [RepositoryItem("165130f5-d0d5-4391-95f1-0f016f4c88c5")]
            public virtual Ranorex.InputTag Psswd
            {
                get
                {
                    return _psswdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Psswd item info.
            /// </summary>
            [RepositoryItemInfo("165130f5-d0d5-4391-95f1-0f016f4c88c5")]
            public virtual RepoItemInfo PsswdInfo
            {
                get
                {
                    return _psswdInfo;
                }
            }

            /// <summary>
            /// The SubmitLogin item.
            /// </summary>
            [RepositoryItem("919b7359-893c-40bd-a5d1-052cda767882")]
            public virtual Ranorex.InputTag SubmitLogin
            {
                get
                {
                    return _submitloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitLogin item info.
            /// </summary>
            [RepositoryItemInfo("919b7359-893c-40bd-a5d1-052cda767882")]
            public virtual RepoItemInfo SubmitLoginInfo
            {
                get
                {
                    return _submitloginInfo;
                }
            }
        }

        /// <summary>
        /// The TranslationResourcesAppFolder folder.
        /// </summary>
        [RepositoryFolder("fc6abb1a-2d49-4d9f-aac6-63a484199323")]
        public partial class TranslationResourcesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _packagesInfo;
            RepoItemInfo _licensesInfo;

            /// <summary>
            /// Creates a new TranslationResources  folder.
            /// </summary>
            public TranslationResourcesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TranslationResources", "/dom[@caption='Translation Resources']", parentFolder, 30000, null, false, "fc6abb1a-2d49-4d9f-aac6-63a484199323", "")
            {
                _packagesInfo = new RepoItemInfo(this, "Packages", ".//div[#'navBar']//a[@innertext='Packages']", 30000, null, "bef985b8-11a5-4641-9827-896c77b0ec8b");
                _licensesInfo = new RepoItemInfo(this, "Licenses", ".//div[#'navBar']//a[@innertext='Licenses']", 30000, null, "e5d90bd6-3488-4db5-b0b7-902f90dd36a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc6abb1a-2d49-4d9f-aac6-63a484199323")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc6abb1a-2d49-4d9f-aac6-63a484199323")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Packages item.
            /// </summary>
            [RepositoryItem("bef985b8-11a5-4641-9827-896c77b0ec8b")]
            public virtual Ranorex.ATag Packages
            {
                get
                {
                    return _packagesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Packages item info.
            /// </summary>
            [RepositoryItemInfo("bef985b8-11a5-4641-9827-896c77b0ec8b")]
            public virtual RepoItemInfo PackagesInfo
            {
                get
                {
                    return _packagesInfo;
                }
            }

            /// <summary>
            /// The Licenses item.
            /// </summary>
            [RepositoryItem("e5d90bd6-3488-4db5-b0b7-902f90dd36a8")]
            public virtual Ranorex.ATag Licenses
            {
                get
                {
                    return _licensesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Licenses item info.
            /// </summary>
            [RepositoryItemInfo("e5d90bd6-3488-4db5-b0b7-902f90dd36a8")]
            public virtual RepoItemInfo LicensesInfo
            {
                get
                {
                    return _licensesInfo;
                }
            }
        }

        /// <summary>
        /// The PackagesAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca88c4c2-cdc1-4a90-88e3-32f481f41631")]
        public partial class PackagesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filterpackageInfo;
            RepoItemInfo _getversionInfo;
            RepoItemInfo _atagdownloadInfo;

            /// <summary>
            /// Creates a new Packages  folder.
            /// </summary>
            public PackagesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Packages", "/dom[@caption='Packages' and @page='packageManagement' and @path='/packageManagement']", parentFolder, 30000, null, false, "ca88c4c2-cdc1-4a90-88e3-32f481f41631", "")
            {
                _filterpackageInfo = new RepoItemInfo(this, "FilterPackage", ".//input[#'filterPackage']", 30000, null, "96786d30-6f0c-4bb2-869b-295d801ba9f3");
                _getversionInfo = new RepoItemInfo(this, "getVersion", ".//div[#'main']/div/div[2]/div[1]/div/div/div[2]/div[2]", 30000, null, "00bc1e88-1fa7-45f9-97b1-c8c2d7a95534");
                _atagdownloadInfo = new RepoItemInfo(this, "ATagDownload", ".//div[@id='packageContent']/div[2]/div[1]/div/div/div[23]/div/div/div/a[2]/i", 30000, null, "b54eac50-e324-415a-86d6-153bf8fdc404");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca88c4c2-cdc1-4a90-88e3-32f481f41631")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca88c4c2-cdc1-4a90-88e3-32f481f41631")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilterPackage item.
            /// </summary>
            [RepositoryItem("96786d30-6f0c-4bb2-869b-295d801ba9f3")]
            public virtual Ranorex.InputTag FilterPackage
            {
                get
                {
                    return _filterpackageInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FilterPackage item info.
            /// </summary>
            [RepositoryItemInfo("96786d30-6f0c-4bb2-869b-295d801ba9f3")]
            public virtual RepoItemInfo FilterPackageInfo
            {
                get
                {
                    return _filterpackageInfo;
                }
            }

            /// <summary>
            /// The getVersion item.
            /// </summary>
            [RepositoryItem("00bc1e88-1fa7-45f9-97b1-c8c2d7a95534")]
            public virtual Ranorex.DivTag getVersion
            {
                get
                {
                    return _getversionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The getVersion item info.
            /// </summary>
            [RepositoryItemInfo("00bc1e88-1fa7-45f9-97b1-c8c2d7a95534")]
            public virtual RepoItemInfo getVersionInfo
            {
                get
                {
                    return _getversionInfo;
                }
            }

            /// <summary>
            /// The ATagDownload item.
            /// </summary>
            [RepositoryItem("b54eac50-e324-415a-86d6-153bf8fdc404")]
            public virtual Ranorex.ITag ATagDownload
            {
                get
                {
                    return _atagdownloadInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The ATagDownload item info.
            /// </summary>
            [RepositoryItemInfo("b54eac50-e324-415a-86d6-153bf8fdc404")]
            public virtual RepoItemInfo ATagDownloadInfo
            {
                get
                {
                    return _atagdownloadInfo;
                }
            }
        }

        /// <summary>
        /// The EnterNameOfFileToSaveToAppFolder folder.
        /// </summary>
        [RepositoryFolder("7fd806c1-0051-4809-8797-022072c63766")]
        public partial class EnterNameOfFileToSaveToAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _text1001Info;

            /// <summary>
            /// Creates a new EnterNameOfFileToSaveTo  folder.
            /// </summary>
            public EnterNameOfFileToSaveToAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnterNameOfFileToSaveTo", "/form[@title~'^Enter\\ name\\ of\\ file\\ to\\ sav']", parentFolder, 30000, null, true, "7fd806c1-0051-4809-8797-022072c63766", "")
            {
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "button[@text='&Save']", 30000, null, "b37f86f5-9e78-47aa-8f3d-2ff9e64864a3");
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", 30000, null, "b1957a08-3a50-4258-9dbc-8c0c21c413cf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7fd806c1-0051-4809-8797-022072c63766")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7fd806c1-0051-4809-8797-022072c63766")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("b37f86f5-9e78-47aa-8f3d-2ff9e64864a3")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("b37f86f5-9e78-47aa-8f3d-2ff9e64864a3")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("b1957a08-3a50-4258-9dbc-8c0c21c413cf")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("b1957a08-3a50-4258-9dbc-8c0c21c413cf")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }
        }

        /// <summary>
        /// The SYSTRAN8TRANSLATORAppFolder folder.
        /// </summary>
        [RepositoryFolder("47ef1190-c397-4a39-8132-62513cd8b419")]
        public partial class SYSTRAN8TRANSLATORAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;

            /// <summary>
            /// Creates a new SYSTRAN8TRANSLATOR  folder.
            /// </summary>
            public SYSTRAN8TRANSLATORAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRAN8TRANSLATOR", "/form[@title='SYSTRAN 8 TRANSLATOR']", parentFolder, 30000, null, true, "47ef1190-c397-4a39-8132-62513cd8b419", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", ".//element[@instance='1']/container[@caption='ShellView']/?/?/listitem[@text='unins000.exe']", 30000, null, "e750e4b9-9bd5-4370-be40-191018c19f94");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("47ef1190-c397-4a39-8132-62513cd8b419")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("47ef1190-c397-4a39-8132-62513cd8b419")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("e750e4b9-9bd5-4370-be40-191018c19f94")]
            public virtual Ranorex.ListItem SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("e750e4b9-9bd5-4370-be40-191018c19f94")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRAN8TRANSLATORUninstallAppFolder folder.
        /// </summary>
        [RepositoryFolder("2042364c-910a-4c6e-9535-803cc7103239")]
        public partial class SYSTRAN8TRANSLATORUninstallAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;
            RepoItemInfo _text65535Info;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _listitem0Info;

            /// <summary>
            /// Creates a new SYSTRAN8TRANSLATORUninstall  folder.
            /// </summary>
            public SYSTRAN8TRANSLATORUninstallAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRAN8TRANSLATORUninstall", "/form[@title~'^SYSTRAN\\ 8\\ ']", parentFolder, 30000, null, true, "2042364c-910a-4c6e-9535-803cc7103239", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 30000, null, "47d3212d-60e5-4e0c-b002-194d26b6a33d");
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 30000, null, "eab0f43f-fc8c-43ea-8253-9de4159c14aa");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "2d1e2768-fc15-465c-bb60-036471b96196");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", ".//element[@instance='1']/container[@caption='ShellView']/container[@class='DirectUIHWND']/listitem[@text>'SYSTRAN 8 TRANSLATOR ']", 30000, null, "30559a8e-89f1-4973-94ea-7bdc8654bff1");
                _listitem0Info = new RepoItemInfo(this, "ListItem0", ".//element[@instance='1']/container[@caption='ShellView']/container[@class='DirectUIHWND']/listitem[@automationid='0']", 30000, null, "87a68644-1d61-4a2a-8355-4e3a493b8ef8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2042364c-910a-4c6e-9535-803cc7103239")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2042364c-910a-4c6e-9535-803cc7103239")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("47d3212d-60e5-4e0c-b002-194d26b6a33d")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("47d3212d-60e5-4e0c-b002-194d26b6a33d")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("eab0f43f-fc8c-43ea-8253-9de4159c14aa")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("eab0f43f-fc8c-43ea-8253-9de4159c14aa")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("2d1e2768-fc15-465c-bb60-036471b96196")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("2d1e2768-fc15-465c-bb60-036471b96196")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("30559a8e-89f1-4973-94ea-7bdc8654bff1")]
            public virtual Ranorex.ListItem SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("30559a8e-89f1-4973-94ea-7bdc8654bff1")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ListItem0 item.
            /// </summary>
            [RepositoryItem("87a68644-1d61-4a2a-8355-4e3a493b8ef8")]
            public virtual Ranorex.ListItem ListItem0
            {
                get
                {
                    return _listitem0Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem0 item info.
            /// </summary>
            [RepositoryItemInfo("87a68644-1d61-4a2a-8355-4e3a493b8ef8")]
            public virtual RepoItemInfo ListItem0Info
            {
                get
                {
                    return _listitem0Info;
                }
            }
        }

        /// <summary>
        /// The OpeningSYSTRAN8TRANSLATORProfessionaAppFolder folder.
        /// </summary>
        [RepositoryFolder("5731371a-f975-4ecb-875c-b3e7a81baf4d")]
        public partial class OpeningSYSTRAN8TRANSLATORProfessionaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _savefileInfo;

            /// <summary>
            /// Creates a new OpeningSYSTRAN8TRANSLATORProfessiona  folder.
            /// </summary>
            public OpeningSYSTRAN8TRANSLATORProfessionaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpeningSYSTRAN8TRANSLATORProfessiona", "/form[@title~'^Opening\\ SYSTRAN\\ 8\\ TRANSLA']", parentFolder, 30000, null, true, "5731371a-f975-4ecb-875c-b3e7a81baf4d", "")
            {
                _savefileInfo = new RepoItemInfo(this, "SaveFile", "button[@accessiblename='Save File']", 30000, null, "056c503c-3003-4d5b-b427-bbf27807737b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5731371a-f975-4ecb-875c-b3e7a81baf4d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5731371a-f975-4ecb-875c-b3e7a81baf4d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SaveFile item.
            /// </summary>
            [RepositoryItem("056c503c-3003-4d5b-b427-bbf27807737b")]
            public virtual Ranorex.Button SaveFile
            {
                get
                {
                    return _savefileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveFile item info.
            /// </summary>
            [RepositoryItemInfo("056c503c-3003-4d5b-b427-bbf27807737b")]
            public virtual RepoItemInfo SaveFileInfo
            {
                get
                {
                    return _savefileInfo;
                }
            }
        }

        /// <summary>
        /// The WizardFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b91ff72-7c40-4fd7-ab88-e312f6cc8c3e")]
        public partial class WizardFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextInfo;
            RepoItemInfo _iaccepttheagreementInfo;
            RepoItemInfo _createadesktopiconInfo;
            RepoItemInfo _installInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new WizardForm  folder.
            /// </summary>
            public WizardFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WizardForm", "/form[@controlname='WizardForm']", parentFolder, 30000, null, true, "2b91ff72-7c40-4fd7-ab88-e312f6cc8c3e", "")
            {
                _nextInfo = new RepoItemInfo(this, "Next", "?/?/button[@accessiblename='Next >']", 30000, null, "f933339e-402e-488a-b32e-b7f609fc1232");
                _iaccepttheagreementInfo = new RepoItemInfo(this, "IAcceptTheAgreement", "element[@controlname='OuterNotebook']//element[@controlname='LicenseAcceptedRadio']/radiobutton[@accessiblename='I accept the agreement']", 30000, null, "91ef9015-90d1-47d9-acf2-c5dffcab9e08");
                _createadesktopiconInfo = new RepoItemInfo(this, "CreateADesktopIcon", "element[@controlname='OuterNotebook']//element[@controlname='SelectTasksPage']/?/?/tree[@accessiblename~'^Select\\ the\\ additional\\ tas']/checkbox[@accessiblename='Create a &desktop icon']", 30000, null, "540cf860-48b9-4116-bc26-90f3d1eddef9");
                _installInfo = new RepoItemInfo(this, "Install", "?/?/button[@accessiblename='Install']", 30000, null, "f1f3b9ac-0d8b-49b5-8456-1b3497e000ed");
                _finishInfo = new RepoItemInfo(this, "Finish", "?/?/button[@accessiblename='Finish']", 30000, null, "fdd4d0ce-b2b0-4b99-95b5-70f908052fa3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b91ff72-7c40-4fd7-ab88-e312f6cc8c3e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b91ff72-7c40-4fd7-ab88-e312f6cc8c3e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("f933339e-402e-488a-b32e-b7f609fc1232")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("f933339e-402e-488a-b32e-b7f609fc1232")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheAgreement item.
            /// </summary>
            [RepositoryItem("91ef9015-90d1-47d9-acf2-c5dffcab9e08")]
            public virtual Ranorex.RadioButton IAcceptTheAgreement
            {
                get
                {
                    return _iaccepttheagreementInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheAgreement item info.
            /// </summary>
            [RepositoryItemInfo("91ef9015-90d1-47d9-acf2-c5dffcab9e08")]
            public virtual RepoItemInfo IAcceptTheAgreementInfo
            {
                get
                {
                    return _iaccepttheagreementInfo;
                }
            }

            /// <summary>
            /// The CreateADesktopIcon item.
            /// </summary>
            [RepositoryItem("540cf860-48b9-4116-bc26-90f3d1eddef9")]
            public virtual Ranorex.CheckBox CreateADesktopIcon
            {
                get
                {
                    return _createadesktopiconInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CreateADesktopIcon item info.
            /// </summary>
            [RepositoryItemInfo("540cf860-48b9-4116-bc26-90f3d1eddef9")]
            public virtual RepoItemInfo CreateADesktopIconInfo
            {
                get
                {
                    return _createadesktopiconInfo;
                }
            }

            /// <summary>
            /// The Install item.
            /// </summary>
            [RepositoryItem("f1f3b9ac-0d8b-49b5-8456-1b3497e000ed")]
            public virtual Ranorex.Button Install
            {
                get
                {
                    return _installInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Install item info.
            /// </summary>
            [RepositoryItemInfo("f1f3b9ac-0d8b-49b5-8456-1b3497e000ed")]
            public virtual RepoItemInfo InstallInfo
            {
                get
                {
                    return _installInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("fdd4d0ce-b2b0-4b99-95b5-70f908052fa3")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("fdd4d0ce-b2b0-4b99-95b5-70f908052fa3")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The DeleteFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("696e833e-cf5b-41db-9776-40430bbc28aa")]
        public partial class DeleteFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new DeleteFile  folder.
            /// </summary>
            public DeleteFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DeleteFile", "/form[@title='Delete File']", parentFolder, 30000, null, true, "696e833e-cf5b-41db-9776-40430bbc28aa", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 30000, null, "525f5674-b92b-4e60-9a57-add75fa75f22");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("696e833e-cf5b-41db-9776-40430bbc28aa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("696e833e-cf5b-41db-9776-40430bbc28aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("525f5674-b92b-4e60-9a57-add75fa75f22")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("525f5674-b92b-4e60-9a57-add75fa75f22")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The SYSTRANLanguageManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("87651c18-525b-4cf0-b3ce-6d57e1f16fc9")]
        public partial class SYSTRANLanguageManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _licensesInfo;
            RepoItemInfo _addproductkeybuttonInfo;
            RepoItemInfo _inputproductkeyInfo;
            RepoItemInfo _submitaddproductkeyInfo;
            RepoItemInfo _onlineactivationInfo;
            RepoItemInfo _productkeyInfo;
            RepoItemInfo _buttontagokInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _licenses1Info;

            /// <summary>
            /// Creates a new SYSTRANLanguageManager  folder.
            /// </summary>
            public SYSTRANLanguageManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SYSTRANLanguageManager", "/dom[@domain='localhost:3500']", parentFolder, 5000, null, false, "87651c18-525b-4cf0-b3ce-6d57e1f16fc9", "")
            {
                _licensesInfo = new RepoItemInfo(this, "Licenses", ".//span[#'errorMessage']/a[@innertext='Licenses']", 30000, null, "1d08394a-fee3-41dd-980c-b7d13e8ec293");
                _addproductkeybuttonInfo = new RepoItemInfo(this, "AddProductKeyButton", ".//button[#'addProductKeyButton']", 30000, null, "93a78946-6262-46a2-9ebe-e19e3406e05d");
                _inputproductkeyInfo = new RepoItemInfo(this, "InputProductKey", ".//textarea[#'inputProductKey']", 30000, null, "d107223d-da42-4c87-8355-438aa3fa2c30");
                _submitaddproductkeyInfo = new RepoItemInfo(this, "SubmitAddProductKey", ".//button[#'submitAddProductKey']", 30000, null, "aeeea990-bf92-4bc8-a0cf-6729e323a42f");
                _onlineactivationInfo = new RepoItemInfo(this, "OnlineActivation", ".//div[#'licenseListContent']/div/div[12]/?/?/button[@innertext='Online Activation']", 30000, null, "c236a67d-72d8-41f4-b5f2-62feb274d372");
                _productkeyInfo = new RepoItemInfo(this, "ProductKey", ".//textarea[#'productKey_']", 5000, null, "54ec2410-79e3-4f87-8b4a-c94a916ae797");
                _buttontagokInfo = new RepoItemInfo(this, "ButtonTagOK", "body/div[6]/div/div/div[2]/button[@innertext='OK']", 30000, null, "851cc47b-557f-47f3-8deb-799a7c5ea8af");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//div[#'licenseListContent']/div/div[13]/?/?/div/a[@innertext='Delete']", 30000, null, "334dd851-cd9f-4440-bad5-f67725ce2210");
                _licenses1Info = new RepoItemInfo(this, "Licenses1", ".//li[#'licencesNavBar']/a[@innertext='Licenses']", 10000, null, "2257135e-21d8-4297-89db-e25afaa8be4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87651c18-525b-4cf0-b3ce-6d57e1f16fc9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87651c18-525b-4cf0-b3ce-6d57e1f16fc9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Licenses item.
            /// </summary>
            [RepositoryItem("1d08394a-fee3-41dd-980c-b7d13e8ec293")]
            public virtual Ranorex.ATag Licenses
            {
                get
                {
                    return _licensesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Licenses item info.
            /// </summary>
            [RepositoryItemInfo("1d08394a-fee3-41dd-980c-b7d13e8ec293")]
            public virtual RepoItemInfo LicensesInfo
            {
                get
                {
                    return _licensesInfo;
                }
            }

            /// <summary>
            /// The AddProductKeyButton item.
            /// </summary>
            [RepositoryItem("93a78946-6262-46a2-9ebe-e19e3406e05d")]
            public virtual Ranorex.ButtonTag AddProductKeyButton
            {
                get
                {
                    return _addproductkeybuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddProductKeyButton item info.
            /// </summary>
            [RepositoryItemInfo("93a78946-6262-46a2-9ebe-e19e3406e05d")]
            public virtual RepoItemInfo AddProductKeyButtonInfo
            {
                get
                {
                    return _addproductkeybuttonInfo;
                }
            }

            /// <summary>
            /// The InputProductKey item.
            /// </summary>
            [RepositoryItem("d107223d-da42-4c87-8355-438aa3fa2c30")]
            public virtual Ranorex.TextAreaTag InputProductKey
            {
                get
                {
                    return _inputproductkeyInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The InputProductKey item info.
            /// </summary>
            [RepositoryItemInfo("d107223d-da42-4c87-8355-438aa3fa2c30")]
            public virtual RepoItemInfo InputProductKeyInfo
            {
                get
                {
                    return _inputproductkeyInfo;
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item.
            /// </summary>
            [RepositoryItem("aeeea990-bf92-4bc8-a0cf-6729e323a42f")]
            public virtual Ranorex.ButtonTag SubmitAddProductKey
            {
                get
                {
                    return _submitaddproductkeyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAddProductKey item info.
            /// </summary>
            [RepositoryItemInfo("aeeea990-bf92-4bc8-a0cf-6729e323a42f")]
            public virtual RepoItemInfo SubmitAddProductKeyInfo
            {
                get
                {
                    return _submitaddproductkeyInfo;
                }
            }

            /// <summary>
            /// The OnlineActivation item.
            /// </summary>
            [RepositoryItem("c236a67d-72d8-41f4-b5f2-62feb274d372")]
            public virtual Ranorex.ButtonTag OnlineActivation
            {
                get
                {
                    return _onlineactivationInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OnlineActivation item info.
            /// </summary>
            [RepositoryItemInfo("c236a67d-72d8-41f4-b5f2-62feb274d372")]
            public virtual RepoItemInfo OnlineActivationInfo
            {
                get
                {
                    return _onlineactivationInfo;
                }
            }

            /// <summary>
            /// The ProductKey item.
            /// </summary>
            [RepositoryItem("54ec2410-79e3-4f87-8b4a-c94a916ae797")]
            public virtual Ranorex.TextAreaTag ProductKey
            {
                get
                {
                    return _productkeyInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The ProductKey item info.
            /// </summary>
            [RepositoryItemInfo("54ec2410-79e3-4f87-8b4a-c94a916ae797")]
            public virtual RepoItemInfo ProductKeyInfo
            {
                get
                {
                    return _productkeyInfo;
                }
            }

            /// <summary>
            /// The ButtonTagOK item.
            /// </summary>
            [RepositoryItem("851cc47b-557f-47f3-8deb-799a7c5ea8af")]
            public virtual Ranorex.ButtonTag ButtonTagOK
            {
                get
                {
                    return _buttontagokInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagOK item info.
            /// </summary>
            [RepositoryItemInfo("851cc47b-557f-47f3-8deb-799a7c5ea8af")]
            public virtual RepoItemInfo ButtonTagOKInfo
            {
                get
                {
                    return _buttontagokInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("334dd851-cd9f-4440-bad5-f67725ce2210")]
            public virtual Ranorex.ATag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("334dd851-cd9f-4440-bad5-f67725ce2210")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Licenses1 item.
            /// </summary>
            [RepositoryItem("2257135e-21d8-4297-89db-e25afaa8be4b")]
            public virtual Ranorex.ATag Licenses1
            {
                get
                {
                    return _licenses1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Licenses1 item info.
            /// </summary>
            [RepositoryItemInfo("2257135e-21d8-4297-89db-e25afaa8be4b")]
            public virtual RepoItemInfo Licenses1Info
            {
                get
                {
                    return _licenses1Info;
                }
            }
        }

        /// <summary>
        /// The ConfirmSaveAsAppFolder folder.
        /// </summary>
        [RepositoryFolder("93f24892-b257-4141-85bf-b3a1b8f9cb56")]
        public partial class ConfirmSaveAsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new ConfirmSaveAs  folder.
            /// </summary>
            public ConfirmSaveAsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConfirmSaveAs", "/form[@title='Confirm Save As']", parentFolder, 5000, null, true, "93f24892-b257-4141-85bf-b3a1b8f9cb56", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/element[@instance='0']/button[@text='&Yes']", 5000, null, "18355e23-1735-4234-8433-70320258427f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93f24892-b257-4141-85bf-b3a1b8f9cb56")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93f24892-b257-4141-85bf-b3a1b8f9cb56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("18355e23-1735-4234-8433-70320258427f")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("18355e23-1735-4234-8433-70320258427f")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The LicensesAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4acb732-f92c-4254-9e4f-6a2ab6bd2781")]
        public partial class LicensesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productkeycopiedtoclipboardInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new Licenses  folder.
            /// </summary>
            public LicensesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Licenses", "/dom[1]", parentFolder, 30000, null, false, "a4acb732-f92c-4254-9e4f-6a2ab6bd2781", "")
            {
                _productkeycopiedtoclipboardInfo = new RepoItemInfo(this, "ProductKeyCopiedToClipboard", ".//div[#'licenseListContent']/div[2]/div[14]//button[@title~'^Product\\ Key\\ copied\\ to\\ cli']", 30000, null, "ac3530e5-e929-4e69-a1e9-d8b98b63aee7");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//div[#'licenseListContent']/div/div[13]//a[@innertext='Delete']", 30000, null, "9fb0d455-b285-42c2-aac5-e381112bc2ef");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "body/div[6]/div/div/div[2]/button[@innertext='Cancel']", 30000, null, "35eb0e84-2fcf-46a2-9d8c-f888c4220156");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4acb732-f92c-4254-9e4f-6a2ab6bd2781")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4acb732-f92c-4254-9e4f-6a2ab6bd2781")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductKeyCopiedToClipboard item.
            /// </summary>
            [RepositoryItem("ac3530e5-e929-4e69-a1e9-d8b98b63aee7")]
            public virtual Ranorex.ButtonTag ProductKeyCopiedToClipboard
            {
                get
                {
                    return _productkeycopiedtoclipboardInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ProductKeyCopiedToClipboard item info.
            /// </summary>
            [RepositoryItemInfo("ac3530e5-e929-4e69-a1e9-d8b98b63aee7")]
            public virtual RepoItemInfo ProductKeyCopiedToClipboardInfo
            {
                get
                {
                    return _productkeycopiedtoclipboardInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("9fb0d455-b285-42c2-aac5-e381112bc2ef")]
            public virtual Ranorex.ATag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("9fb0d455-b285-42c2-aac5-e381112bc2ef")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("35eb0e84-2fcf-46a2-9d8c-f888c4220156")]
            public virtual Ranorex.ButtonTag Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("35eb0e84-2fcf-46a2-9d8c-f888c4220156")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}